finos/symphony-bdk-java

src/main/java/authentication/SymBotRSAAuth.java

Hi @manucaicedo 
this is a minor PR to remove debug outputs from System.out. I think we can also consider using the logger to display exception stack traces WDYT ?
I started using this lib to prepare the hackathon, it's super useful to be quickly set up ! 👍

removed System.out.println()

---

README.md

We can see the rendering here https://github.com/symphony-jeremy/symphony-api-client-java/tree/syntax-highlighting-readme

Added syntax highlighting in README.md

---

src/main/java/authentication/AuthEndpointConstants.java
src/main/java/authentication/SymExtensionAppAuth.java
src/main/java/authentication/SymExtensionAppRSAAuth.java
src/main/java/configuration/SymConfig.java
src/main/java/utils/CertificateUtils.java

This commit contains a new constant and new class to authenticate the extension app using a RSA certificate.

RSA Extension App authentication

---

src/main/java/authentication/SymBotAuth.java
src/main/java/authentication/SymBotRSAAuth.java
src/main/java/configuration/SymConfig.java

KM Auth for RSA was not using proxyClient. Changed it to match cert auth code.

Changed SymBotRSAAuth to use proxy for KM Auth

---

src/main/java/authentication/SymExtensionAppRSAAuth.java

This commit contains a fix of extension app authentication using RSA adding two parameters on the request.

fixing the rsa parameters

---

pom.xml
src/main/java/clients/symphony/api/DatafeedClient.java
src/test/resources/logback-test.xml

Adding in info logging for a datafeed create and debug logging for a read

add in info logging for creation of datafeed and debug for reading. Also add logback config for tests

---

README.md
src/main/java/configuration/SymConfig.java
src/main/java/services/DatafeedEventsService.java
src/main/java/utils/HttpClientBuilderHelper.java
src/main/resources/config.json

improve configuration by
removing hardcoded p12 references 
allow jars on the classpath to be loaded
include datafeed threadpool size in configuration
include datafeed error timeout value in configuration

Update config properties

---

README.md
src/main/java/authentication/SymBotAuth.java
src/main/java/authentication/SymBotRSAAuth.java
src/main/java/authentication/SymExtensionAppAuth.java
src/main/java/authentication/SymExtensionAppRSAAuth.java
src/main/java/authentication/SymOBOAuth.java
src/main/java/authentication/SymOBOUserAuth.java

cleaning up all Symauth classes (namely error logging) and updating the readme to indicate you can set config client side

Symbot authentication classes - general cleanup of code

---

src/main/java/clients/symphony/api/AdminClient.java

Fix AdminUserInfo casting

---

src/main/java/authentication/SymBotAuth.java
src/main/java/clients/SymBotClient.java
src/main/java/clients/symphony/api/AdminClient.java
src/main/java/clients/symphony/api/DatafeedClient.java
src/main/java/services/DatafeedEventsService.java
src/main/java/services/FirehoseService.java
src/main/java/utils/DataProvider.java
src/main/java/utils/SymMessageParser.java

All errors should be properly logged and not called as printstacktraces. This merge fixes all remaining in the codebase and should close off issue #5

cleaning up all remaining printstacktraces

---

README.md
src/main/java/authentication/SymBotAuth.java
src/main/java/authentication/SymBotRSAAuth.java
src/main/java/authentication/SymExtensionAppAuth.java
src/main/java/authentication/SymExtensionAppRSAAuth.java
src/main/java/authentication/SymOBOAuth.java
src/main/java/clients/SymBotClient.java
src/main/java/clients/SymOBOClient.java
src/main/java/configuration/SymConfig.java

Added pod proxy configuration and updated readme

Added pod proxy configuration

---

README.md
pom.xml
src/main/java/authentication/SymBotAuth.java
src/main/java/authentication/SymBotRSAAuth.java

Make Session Auth respect the Pod Proxy Config

Make Session Auth respect the Pod Proxy Config

---

pom.xml
src/main/java/services/DatafeedEventsService.java
src/main/java/utils/HttpClientBuilderHelper.java

Clean Up Dependencies + Fix Truststore Path Bug

Clean Up Dependencies + Fix Truststore Path Bug

---

src/main/java/clients/symphony/api/DatafeedClient.java
src/main/java/services/DatafeedEventsService.java

Removing some return nulls as can lead to nullpointer errors

Do not return null explicitly as can lead to nullpointer errors

---

src/main/java/model/StreamTypes.java

There's a small mistake on StreamType enumerator and it'll fix it.

Fixing the StreamType enum

---

README.md
pom.xml
src/main/java/authentication/AuthEndpointConstants.java
src/main/java/authentication/SymExtensionAppAuth.java
src/main/java/authentication/SymExtensionAppRSAAuth.java
src/main/java/authentication/extensionapp/InMemoryTokensRepository.java
src/main/java/authentication/extensionapp/TokensRepository.java
src/main/java/utils/JwtHelper.java

Adding RSA pod certificate path URL;
Extracting the JWT validation method to JwtHelper;
Setting up an in memory repository to store auth tokens that can be replaced by another repository given by the user. It must implement the TokensRepository interface;
Implementing validateTokens() and verifyJwt() methods for SymExtensionAppRSAAuth.

Ext app rsa auth

---

src/main/java/authentication/jwt/AuthenticationFilter.java

Updating filter pattern;
Extracting pattern matcher to method;
Adding return after first .doFilter call.

JWT filter

---

src/main/java/authentication/SymExtensionAppRSAAuth.java

SymExtensionAppRSAAuth only allows to specify the app RSA key in SymConfig as a path to the RSA file. This is an issue in case the RSA key is hosted somewhere not reachable by the supported SymConfig path. Or if the RSA key is generated on the fly.
A more flexible way, to complement SymConfig, is to pass to SymExtensionAppRSAAuth a PrivateKey object so that SymExtensionAppRSAAuth does not need to worry to support all possible ways a private key is fetched.

(#58) Added constructor that takes as argument the RSA PrivateKey object

---

src/main/java/authentication/SymBotAuth.java
src/main/java/authentication/SymBotRSAAuth.java
src/main/java/authentication/SymExtensionAppAuth.java
src/main/java/authentication/SymExtensionAppRSAAuth.java
src/main/java/clients/SymBotClient.java
src/main/java/clients/SymOBOClient.java
src/main/java/configuration/SymConfig.java
src/main/java/utils/HttpClientBuilderHelper.java
src/test/java/it/clients/symphony/api/DatafeedClientTest.java
src/test/resources/bot-config.json

Added configurable connection timeout for all requests performed by Symphony API Client.
Updated integration tests
Cleaned up some logics

connection timeout support

---

src/main/java/configuration/SymLoadBalancedConfig.java

Propagating the connectionTimeout for LB config

add connectionTimeout for LB config

---

src/main/java/configuration/SymConfigLoader.java
src/main/java/model/HealthcheckResponse.java

SDK-62: Error loading config.json from resources
SDK-63: HealthcheckResponse class does not ignore unknown fields

Fix config loader and HealthCheckResponse bugs

---

src/main/java/model/RoomSearchQuery.java

Adding missing RoomSearchQuery parameters: sortOrder and subType (#109)

---

README.md
src/main/java/configuration/SymConfig.java
src/main/java/utils/DataProvider.java

PLAT-9037 Creating new supportedUriSchemes property to support custom URI schemes (#110)

---

src/main/java/clients/symphony/api/MessagesClient.java
src/main/java/clients/symphony/api/constants/AgentConstants.java
src/main/java/model/InboundMessage.java
src/test/java/it/clients/symphony/api/MessagesClientTest.java

- [Jira Ticket](https://perzoinc.atlassian.net/browse/CES-898)
- We have created an API to get the message using the message id
- Added Unit Test for the same API
- Added `sharedMessage`, `disclaimer` & `sid` fields to the `InboundMessage` following V4Message structure on the agent

 CES-898: Created an API to get message by id along with the disclaimer text

---

src/main/java/clients/symphony/api/MessagesClient.java
src/main/java/clients/symphony/api/constants/AgentConstants.java
src/main/java/model/InboundMessage.java
src/test/java/it/clients/symphony/api/MessagesClientTest.java

- [Jira Ticket](https://perzoinc.atlassian.net/browse/CES-898)
- We have created an API to get the message using the message id
- Added Unit Test for the same API
- Added `sharedMessage`, `disclaimer` & `sid` fields to the `InboundMessage` following V4Message structure on the agent

CES-898: Created an API to get message by id along with the disclaimer text

---

src/main/java/utils/SymMessageParser.java
src/test/java/utils/SymMessageParserTest.java

Add more filters to handle bad structure of received data.

PLAT-9069: Handle null for bad data structure to getMentions

---

src/test/java/it/clients/symphony/api/HealthcheckClientTest.java

check unknown fields returned by healtcheck api are ignored

Added unittest for SDK-63

---

src/main/java/model/events/MessageSent.java
src/main/java/model/events/RoomCreated.java
src/main/java/model/events/RoomDeactivated.java
src/main/java/model/events/RoomMemberDemotedFromOwner.java
src/main/java/model/events/RoomMemberPromotedToOwner.java
src/main/java/model/events/RoomReactivated.java
src/main/java/model/events/RoomUpdated.java
src/main/java/model/events/UserJoinedRoom.java
src/main/java/model/events/UserLeftRoom.java
src/main/java/services/DatafeedEventsService.java

* SDK-59 Add Initiator to RoomListener callback
* SDK-59 Add Initiator to RoomListener callbacks
* Remove unused import
(cherry picked from commit 4b740eab079078cc1122d5ab9180fcd008120ba6)

Backport: SDK-59 Add Initiator to RoomListener callback (#126)

---

src/main/java/clients/symphony/api/APIClient.java
src/test/java/it/clients/symphony/api/StreamsClientTest.java

* Add repo owners
* SDK-90: Handle null content-type 401 error response
* Remove unused import
* Change ObjectMapper to static
* Handle response content not-json formatted
* Log errorString not in json format
(cherry picked from commit 4b9b6ea1bd3dd174ac38eb3a14a546b3c0267f79)

SDK-90 Backporting: Handle null content-type 401 error response

---

src/main/java/model/events/SymphonyElementsAction.java

* Map and expose formMessageId
* Corrected input name of setFormMessageId
(cherry picked from commit aef16f1496011b9b323fe8ce666a969cd66b1230)

SDK-96: Map and expose formMessageId (#119)

---

src/main/java/model/UserInfo.java

* feature(User): Add AccountType on UserInfo
* feature(pom): Rollback version on pom

feature(User): Add AccountType on UserInfo (#151)

---

.circleci/config.yml

Issue and solution described here : https://issues.apache.org/jira/browse/MDEP-516

Fixed circle ci command: mvn dependency:go-offline

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkExtAppConfig.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigTest.java

Don't know how to test SymphonyBdk as it has many dependencies.

APP-2998 Make OBO configuration optional

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/StreamService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/constant/AttachmentSort.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/stream/StreamServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/JsonHelper.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/MockApiClient.java
symphony-bdk-core/src/test/resources/stream/list_attachments.json
symphony-bdk-core/src/test/resources/stream/list_stream.json
symphony-bdk-core/src/test/resources/stream/room_detail.json
symphony-bdk-core/src/test/resources/stream/room_search.json
symphony-bdk-core/src/test/resources/stream/v2_admin_stream_list.json
symphony-bdk-core/src/test/resources/stream/v2_membership_list.json
symphony-bdk-core/src/test/resources/stream/v2_stream_attributes.json
symphony-bdk-core/src/test/resources/stream/v3_room_detail.json

Wrap the stream APIs in StreamService class
Create an entry to stream service in SymphonyBdk by calling method SymphonyBdk#streams
Added unittest
Mocking apiclient by using Mockito to speed up test
Documentation added

APP-2982: Stream Service Implementation

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/command/CommandFilterImpl.java

if there is a null commandMatcher bots will not respond to any commands even if commandMatcher is not null

Fixed an issue where bot will not respond to any commands 

---

symphony-bdk-legacy/sms-sdk-renderer-java/pom.xml

This is to fix snyk issues here : https://app.snyk.io/org/developer-experience-ab1/project/23c9688f-3095-4de8-810b-318df3d736e4

APP-3049: upgraded handlebars to 4.2.0

---

symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/MockApiClient.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/MockApiClientException.java

Throw MockApiClientException when calling wrong path or wrong method

Enhancement for MockApiClient

---

symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/MockApiClient.java

Update user service unittest using MockApiClient

Speed up unittest by using MockApiClient

---

symphony-bdk-legacy/symphony-api-client-java/src/test/java/services/AbstractDatafeedEventsServiceTest.java

SDK-137(https://perzoinc.atlassian.net/browse/SDK-137?atlOrigin=eyJpIjoiNTBiZmU0ZmM4OTliNGQyYjhhOTljNDhlMzllYTlhZmMiLCJwIjoiaiJ9)

Sdk-137 Stabilization of AbstractDatafeedEventsServiceTest

---

symphony-bdk-legacy/symphony-api-client-java/src/test/java/utils/DataProviderTest.java

[SDK-141](https://perzoinc.atlassian.net/browse/SDK-141)
Added test for package utils.DataProvider

SDK-141 Java SDK: Create test coverage for the class utils.DataProvider

---

build.gradle
jenkins/Jenkinsfile-release
jenkins/Jenkinsfile-release-legacy
symphony-bdk-legacy/build.gradle

[APP-3106](https://perzoinc.atlassian.net/browse/APP-3106)
Removed projectVersion parameter in gradle and jenkins files
Project version will be the one taken from the gradle.build files

APP-3106: Removed projectVersion parameter in gradle and jenkins files

---

build.gradle
symphony-bdk-legacy/build.gradle

[APP-3164](https://perzoinc.atlassian.net/browse/APP-3164)
Bumped release versions in order to release Java BDK 1.4.0.BETA

APP-3164: Release Java BDK 1.4.0.BETA

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/ServiceFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/presence/OboPresenceService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/presence/PresenceService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/presence/constant/PresenceStatus.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/StreamService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/presence/PresenceServiceTest.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkServiceConfig.java

[APP-3121](https://perzoinc.atlassian.net/browse/APP-3121)
Presence Service feature with OBO enabled

APP-3121: Presence Service feature

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/OboServices.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/ServiceFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/connection/ConnectionService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/connection/OboConnectionService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/connection/constant/ConnectionStatus.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/OboServicesTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/ServiceFactoryTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/SymphonyBdkTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/connection/ConnectionServiceTest.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkServiceConfig.java

[APP-2984](https://perzoinc.atlassian.net/browse/APP-2984)
* ConnectionService exposing connection endpoints.
* SymphonyBdk#connections to get the connection service from bdk entry point.
* ConnectionService spring boot autoconfiguration.

APP-2984: Connection Service feature

---

symphony-bdk-legacy/build.gradle
symphony-bdk-legacy/symphony-bdk-bot-sdk-java/build.gradle

Fix legacy publising configuration

---

symphony-bdk-legacy/build.gradle

(cherry picked from commit 5eae54be7ef703cde558c579194c36a7a787d1a5)

Adding signing step in legacy build

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/symphony/DatafeedClientImpl.java

[APP-3199](https://perzoinc.atlassian.net/browse/APP-3199)
Add option to enable/disable datafeed polling

add option to enable/disable datafeed polling

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/OboUserService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/AuthMain.java

Update UserService according to this changes in swagger spec.
https://github.com/symphonyoss/symphony-api-spec/commit/df84837f6fa9f31cda9b0a33e3ce86b705c0ee3d#diff-729955798b87f663f4d7efeb58ca0da55bf2bd39f913d5372e0258304e239176L1457

Update UserService according to the changes in swagger spec

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/OboUserService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/ServiceExampleMain.java

[APP-3133](https://perzoinc.atlassian.net/browse/APP-3133)
Add follow/unfollowUser api to UserService

APP-3133: Add follow/unfollowUser api to UserService

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/PaginatedService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/model/PaginationAttribute.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/model/StreamPaginationAttribute.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/OboStreamService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/StreamService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/OboUserService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/stream/StreamServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java

[APP-3183](https://perzoinc.atlassian.net/browse/APP-3183)
Create PaginationAttribute and StreamPaginationAttribute for defining (skip,limit) for default pagination and (chunkSize, totalSize) for stream pagination.
Each listing endpoint will have 2 methods for default pagination with and w/o PaginationAttribute and 2 methods for stream pagination with and w/o StreamPaginationAttribute.
Annotate method using @Nonnull and @Nullable.

APP-3183: Pagination strategy on StreamService

---

symphony-bdk-legacy/symphony-api-client-java/src/test/java/authentication/SymExtensionAppAuthTest.java
symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/event/EventListener.java
symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/symphony/authentication/CertificateExtensionAppAuthenticator.java

[APP-3246](https://perzoinc.atlassian.net/browse/APP-3246)

APP-3246: Certificate auth and disabling datafeed polling

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/model/CursorPaginationAttribute.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/model/RangePaginationAttribute.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/OboUserService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/ServiceExampleMain.java

[APP-3134](https://perzoinc.atlassian.net/browse/APP-3134)
Add list followers/following user api to UserService

APP-3134: Add list followers/following user api to UserService

---

build.gradle
symphony-bdk-legacy/build.gradle

[APP-3258](https://perzoinc.atlassian.net/browse/APP-3258)
Deliver 1.5.0.BETA

APP-3258: Bumped version to 1.5.0.BETA

---

build.gradle
symphony-bdk-legacy/build.gradle

[APP-3258](https://perzoinc.atlassian.net/browse/APP-3258)
Bumped version to 1.5.0-SNAPSHOT

Bumped version to 1.6.0-SNAPSHOT

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/OboUserService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/AuthMain.java

Update UserService according to the changes in swagger spec (#315)
(cherry picked from commit 00fe031cd7ab2f37c333ff8f16a08656c668962e)

Update UserService according to the changes in swagger spec (#315)

---

symphony-bdk-legacy/symphony-api-client-java/src/test/java/authentication/SymExtensionAppAuthTest.java
symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/event/EventListener.java
symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/symphony/authentication/CertificateExtensionAppAuthenticator.java

[Ticket number](link to ticket)

Certificate auth and disabling datafeed polling

---

symphony-bdk-legacy/build.gradle

[APP-3254](https://perzoinc.atlassian.net/browse/APP-3254)
Bumped legacy SDK version to 1.3.3

APP-3254: Bumped legacy version to 1.3.3

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/ServiceFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/application/ApplicationManagementService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/application/ApplicationService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/ServiceFactoryTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/SymphonyBdkTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/application/ApplicationManagementServiceTest.java
symphony-bdk-core/src/test/resources/application/create_application.json
symphony-bdk-core/src/test/resources/application/get_application.json
symphony-bdk-core/src/test/resources/application/list_app_entitlements.json
symphony-bdk-core/src/test/resources/application/update_application.json
symphony-bdk-core/src/test/resources/application/user_apps.json
symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/ServiceExampleMain.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkServiceConfig.java

[APP-3122](https://perzoinc.atlassian.net/browse/APP-3122)
Implement the application management service

APP-3122: Implement the application management service

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java
symphony-bdk-core/src/test/resources/message/blast_message.json

[APP-3251](https://perzoinc.atlassian.net/browse/APP-3251)
Integrated blast message endpoint

APP-3251: Integrated blast message endpoint

---

symphony-bdk-legacy/symphony-api-client-java/src/main/java/authentication/SymOBOAuth.java
symphony-bdk-legacy/symphony-api-client-java/src/test/java/authentication/SymOBOAuthTest.java

[159](https://perzoinc.atlassian.net/browse/SDK-159?atlOrigin=eyJpIjoiMGRhZjUyM2Q5OWZjNGQ5MDg3M2FhNzRiYzllZjY1OGIiLCJwIjoiaiJ9)
- The verifications of the exceptions is impossible to do
- I overloaded the contsuctors of the class to try to decrease execution time

SDK-159 Java-SDK: Create test coverage for authentication.SymOBOAuth

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/extapp/authentication/AppAuthController.java
symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/extapp/authentication/AppAuthControllerTest.java

[163](https://perzoinc.atlassian.net/browse/SDK-163?atlOrigin=eyJpIjoiODE3NTEwMGQzYmJhNDdjMzg3YWM1NzY5MTVjN2Q4MTAiLCJwIjoiaiJ9)

SDK-163 Java BDK: Create test coverage for AppAuthController

---

docs/message.md
docs/spring-boot/core-starter.md

Update Message API documentation

Update Message API documentation

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/lib/jsonmapper/JsonMapperTest.java

[SDK-169](https://perzoinc.atlassian.net/browse/SDK-169)
Added unit test for JsonMapperImpl

SDK-169 Java BDK: Create test coverage for com.symphony.bdk.bot.sdk.lib.jsonmapper.JsonMapperImpl

---

symphony-bdk-bom/build.gradle
symphony-bdk-http/symphony-bdk-http-jersey2/build.gradle
symphony-bdk-http/symphony-bdk-http-webclient/build.gradle
symphony-bdk-legacy/build.gradle
symphony-bdk-legacy/sms-sdk-renderer-java/build.gradle
symphony-bdk-legacy/symphony-api-client-java/build.gradle

- [APP-3067](https://perzoinc.atlassian.net/browse/APP-3067)
- [APP-3067](https://perzoinc.atlassian.net/browse/APP-3043)
- [APP-3067](https://perzoinc.atlassian.net/browse/APP-3155)
General upgrade of project dependencies.

APP-3067 Dependencies upgrade to fix Snyk vulnerabilities

---

docs/authentication.md
docs/configuration.md
docs/getting-started.md
docs/spring-boot/app-starter.md
docs/spring-boot/core-starter.md
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/AuthenticatorFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/ApiClientFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkAuthenticationConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkCertificateConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkRsaKeyConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkSslConfig.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/AuthenticatorFactoryTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/ApiClientFactoryTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigTest.java
symphony-bdk-examples/bdk-app-spring-boot-example/src/main/resources/application.yaml
symphony-bdk-examples/bdk-spring-boot-example/src/main/resources/application.yaml

[APP-3071](https://perzoinc.atlassian.net/browse/APP-3071)
Update the configuration field for privateKey and certificate

APP-3071: Update the configuration field for privateKey and certificate

---

docs/configuration.md
symphony-bdk-bom/build.gradle
symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/exception/FatalActivityExecutionException.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/ApiClientFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkAuthenticationConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkCertificateConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkClientConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkProxyConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkServerConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkSslConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/model/Attachment.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/ApiClientFactoryTest.java
symphony-bdk-examples/bdk-core-examples/src/main/resources/proxy/withBasicAuthentication/Dockerfile
symphony-bdk-examples/bdk-core-examples/src/main/resources/proxy/withBasicAuthentication/config_proxy.yaml
symphony-bdk-examples/bdk-core-examples/src/main/resources/proxy/withBasicAuthentication/docker-compose.yaml
symphony-bdk-examples/bdk-core-examples/src/main/resources/proxy/withBasicAuthentication/passwd
symphony-bdk-examples/bdk-core-examples/src/main/resources/proxy/withBasicAuthentication/squid.conf
symphony-bdk-examples/bdk-core-examples/src/main/resources/proxy/withoutAuthentication/config_proxy.yaml
symphony-bdk-examples/bdk-core-examples/src/main/resources/proxy/withoutAuthentication/docker-compose.yaml
symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/ApiClientBuilder.java
symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/HttpClient.java
symphony-bdk-http/symphony-bdk-http-jersey2/build.gradle
symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2.java
symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClient.java
symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClientTest.java

[APP-3230](https://perzoinc.atlassian.net/browse/APP-3230)
Implemented proxy support for webclient and jersey2 clients.
Depends on a test with a local proxy -> docker-compose.yaml files for running local proxies put in this PR.

APP-3230: Proxy support

---

symphony-bdk-legacy/symphony-api-client-java/src/main/java/authentication/SymBotAuth.java
symphony-bdk-legacy/symphony-api-client-java/src/main/java/clients/symphony/api/APIClient.java
symphony-bdk-legacy/symphony-api-client-java/src/test/java/authentication/SymBotAuthTest.java
symphony-bdk-legacy/symphony-api-client-java/src/test/resources/bot-config.json

[SDK-157](https://perzoinc.atlassian.net/browse/SDK-157)
Added unit test for **SymBotAuth**.

SDK-157 Java SDK: create test coverage for authentication.SymBotAuth

---

.devx-cicd/config.yaml
build.gradle

[APP-3296](https://perzoinc.atlassian.net/browse/APP-3296)
See https://github.com/micaste/symphony-api-client-java/blob/APP-3296/.devx-cicd/config.yaml
Introducing the first steps of the devx-cicd builder
My plan is to keep that work on a separate branch for now, but I will still create PRs for merging on it

APP-3296 Add .devx-cicd/config.yaml file, that builds snapshot artifacts

---

symphony-bdk-legacy/sms-sdk-renderer-java/src/test/java/it/services/SmsRendererTest.java

Modify way of reading file to be independent from where the process is run
[SDK-173](https://perzoinc.atlassian.net/browse/SDK-173?atlOrigin=eyJpIjoiYTAxYTg5N2U4N2ZkNDJjOGIxNDdjMWVmYjZmNTk0YmQiLCJwIjoiaiJ9)

SDK-173-bis Java SDK: create test coverage for the class SmsRenderer (modify way of reading files)

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/command/matcher/EscapedCharacter.java
symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/command/matcher/EscapedCharacterTest.java

[SDK-174](https://perzoinc.atlassian.net/browse/SDK-174)
Added unit test for **_EscapedCharacter_**.

SDK-174 - Java SDK: create test coverage for command.matcher.EscapedCharacter

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/AuthenticatorFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/BotAuthenticatorCertImpl.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/BotAuthenticatorRsaImpl.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorCertImpl.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/OboAuthenticatorCertImpl.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/OboAuthenticatorRsaImpl.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/model/ExtensionAppAuthenticateRequest.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecovery.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecoveryBuilder.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/JwtHelperTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractBotAuthenticatorTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractExtensionAppAuthenticatorTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractOboAuthenticatorTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/BotAuthenticatorRsaImplTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorRsaImplTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/OboAuthenticatorRsaImplTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/loadbalancing/LoadBalancingStrategyTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigLoaderTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/retry/resilience4j/Resilience4jRetryWithRecoveryTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedServiceV1Test.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/OnDiskDatafeedIdRepositoryTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/InMemoryDatafeedIdRepository.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/RsaTestHelper.java

Cleaning up warnings and making the tests faster for bdk-core module

IDEA warnings

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/symphony/UsersClientlmplTest.java

[SDK-180](https://perzoinc.atlassian.net/browse/SDK-180?atlOrigin=eyJpIjoiM2VmNjAwNzBmOTllNDU0MzkwNmViMGViMGFhMzg1MDEiLCJwIjoiaiJ9)

SDK-180 Java BDK: Create test coverage for sdk.symphony.UsersClientImpl

---

build.gradle
symphony-bdk-legacy/build.gradle

PLAT-10255
Bumped versions to 1.7.0-SNAPSHOT

PLAT-10255 Bumped version to 1.7.0-SNAPSHOT

---

build.gradle
symphony-bdk-legacy/build.gradle

PLAT-10255
Bumped version to 1.6.0.BETA for releasing

PLAT-10255 Bumped version to 1.6.0.BETA

---

docs/tech/api-change-management.md
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/AuthenticatorFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkAuthenticationConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkSslConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/util/DeprecationLogger.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/util/DeprecationLoggerTest.java
symphony-bdk-examples/bdk-core-examples/src/main/resources/log4j.properties
symphony-bdk-examples/bdk-core-examples/src/main/resources/logback.xml

PLAT-9981
Added documentation file explaining our change management policy.
Added conditional `WARN` logs in case deprecated configuration fields are used.

PLAT-9981: Documented change management policy

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/symphony/StreamsClientImplTest.java

[SDK-179](https://perzoinc.atlassian.net/browse/SDK-179?atlOrigin=eyJpIjoiZTliM2ZjYjc0YjZhNGNkOGI2ZGZlMGZiZjBkZTZhMjkiLCJwIjoiaiJ9)

SDK-179 Java BDK: Create test coverage for sdk.symphony.StreamsClientImpl

---

symphony-bdk-legacy/symphony-api-client-java/src/main/java/internal/FileHelper.java
symphony-bdk-legacy/symphony-api-client-java/src/test/java/internal/FileHelperTest.java

PLAT-10261
Fixed path joining for classpath resources on Windows.

PLAT-10261: Fixed classpath paths for windows platform

---

build.gradle

PLAT-10295
Prepare the 2.0.0 GA with a first release candidate

PLAT-10295: Release 2.0.0-RC1

---

build.gradle

PLAT-10295
Prepare the 2.0.0 GA with a first release candidate
(Got the version number wrong)

PLAT-10295: Release 2.0.0.RC1

---

build.gradle

PLAT-10295
Bump version for 2.0.0 release

PLAT-10295: Bump version for 2.0.0 release

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/sse/SseControllerTest.java

[SDK-187](https://perzoinc.atlassian.net/browse/SDK-187)
Added unit test for sse.SseController.

SDK-187 Java SDK: create coverage for sse.SseController

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/HelpCommand.java

[PLAT-10144](https://perzoinc.atlassian.net/browse/PLAT-10144)
Check command list is not empty before sending response

PLAT-10144: Check command list is not empty before sending response

---

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/sse/SsePublisherRouterImplTest.java

[SDK-189](https://perzoinc.atlassian.net/browse/SDK-189?atlOrigin=eyJpIjoiZTdiMjc4MTE1ZWU2NDk0MDk0YTczYjY2ZGUyMmM1NjkiLCJwIjoiaiJ9)

SDK-189 Java BDK: Create coverage for sse.SsePublisherRouterImpl

---

symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/HelpCommandTest.java

[PLAT-10144](https://perzoinc.atlassian.net/browse/PLAT-10144)
Added unittest

PLAT-10144: Added unittest

---

symphony-bdk-core/build.gradle
symphony-bdk-legacy/build.gradle
symphony-bdk-legacy/sms-sdk-renderer-java/build.gradle
symphony-bdk-legacy/symphony-api-client-java/build.gradle
symphony-bdk-legacy/symphony-api-client-java/src/main/java/internal/FileHelper.java
symphony-bdk-legacy/symphony-api-client-java/src/test/java/internal/FileHelperTest.java

PLAT-10423
Deliver legacy BDK 1.3.5 containing : 
* #388
* #358 (changes restricted to symphony-bdk-legacy)
* #397

PLAT-10423: Deliver BDK 1.3.5

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/ApiClientFactory.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/ApiClientFactoryTest.java

PLAT-10478
Fixed connection pool per route. Added unit tests

PLAT-10478: Fixed connection pool per route

---

.whitesource
whitesource.config

WhiteSource configuration from https://github.com/finos/project-blueprint

[FINOS] Configure WhiteSource

---

.github/workflows/build.yml

Relates to https://github.com/finos/symphony-bdk-java/issues/452
Adding GH Actions in replacement of CircleCI.

#452 Adding build workflow

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/release.yml
build.gradle

Closes https://github.com/finos/symphony-bdk-java/issues/459
Automated legacy release workflow using Github Actions. 
[`release.yml`](https://github.com/finos/symphony-bdk-java/blob/main/.github/workflows/release.yml) workflow is the exact same from `main` and `rc` branches.

#459 Automated legacy release using Github Actions

---

.github/workflows/build.yml
docs/configuration.md
docs/datafeed.md
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkDatafeedConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkRetryConfig.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RecoveryStrategy.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecovery.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/resilience4j/Resilience4jRetryWithRecovery.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/BdkRetryConfigTestHelper.java
symphony-bdk-core/src/test/resources/config/config.yaml
symphony-bdk-core/src/test/resources/config/df_retry_config.yaml

Backported from https://github.com/finos/symphony-bdk-java/pull/469

#464 Infinite number of attempts for the Datafeed retry configuration

---

symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/util/ApiUtils.java
symphony-bdk-http/symphony-bdk-http-api/src/test/java/com/symphony/bdk/http/api/HttpClientTest.java

Closes #471 
Updated User-Agent value to comply with RFC7231

#471: Updated User-Agent value to comply with RFC7231

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/OboMessageService.java

#485 Added message suppress endpoint to OboMessageService

---

.whitesource

First we want to focus on the most important ones

Create security issues only for HIGH vulnerabilities

---

docs/datafeed.md

Document how DF loop should be stopped when the bot is stopped.

Doc: DF loop shutdown

---

docs/configuration.md
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigLoader.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigParser.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigParserTest.java
symphony-bdk-core/src/test/resources/config/config_lb_properties.yaml
symphony-bdk-core/src/test/resources/config/config_properties.json
symphony-bdk-core/src/test/resources/config/config_properties.yaml

fixes https://github.com/finos/symphony-bdk-java/issues/506
Allow environment variables in config files

Allow environment variables in config file

---

build.gradle
docs/configuration.md
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigLoader.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigParser.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigParserTest.java
symphony-bdk-core/src/test/resources/config/config_lb_properties.yaml
symphony-bdk-core/src/test/resources/config/config_properties.json
symphony-bdk-core/src/test/resources/config/config_properties.yaml

https://github.com/finos/symphony-bdk-java/pull/507 backport

#507 backport to 2.1 rc

---

build.gradle

[#523](https://github.com/finos/symphony-bdk-java/issues/523)
Upgraded jersey dependency to 2.34 and Commons to 2.7

PLAT-10897 PLAT-10898 fix Jersey and Commons dependencies in Legacy

---

symphony-bdk-bom/build.gradle

[#521](https://github.com/finos/symphony-bdk-java/issues/521)
Upgraded jersey dependency to 2.34

PLAT-10897 Upgraded jersey dependency to 2.34

---

symphony-bdk-bom/build.gradle
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle

Minor upgrade to keep up with Spring Boot releases

Upgrade to Spring Boot 2.4.6 / Mockserver 5.11.2

---

build.gradle

Bump legacy project's version to 1.7.1 after security vulnerabilities fix.

Bump legacy version

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/HelpCommand.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/HelpCommandTest.java

This PR is related to [#533](https://github.com/finos/symphony-bdk-java/issues/533)
Added mention bot part in built-in help command's description

PLAT-10920 :  Return build-in /help command in the list of commands

---

docs/migration.md

Generated html code was not rendering correct as the markdown inside html tags was not converted and processed as string. To fix that, we copy the final generated html code in .md file
[PLAT-10947](https://perzoinc.atlassian.net/browse/PLAT-10947)

PLAT-10947 Correct migration guide code snippets on documentation

---

symphony-bdk-core/build.gradle
symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/loadbalancing/LoadBalancingStrategyTest.java
templates/README.md
templates/api.mustache
templates/pojo.mustache

To make it work with recent versions of Gradle.
Templates had to be updated using the latest changes from OpenAPI
generator repository.
Also better define task dependencies to avoid Gradle warnings.
---
Fix slow load balancing test
By default retries are performed, make it retry only once.
Also clean up Sonar/IDEA warnings.

Update OpenAPI generator

---

symphony-api-client-java/src/main/java/utils/HttpClientBuilderHelper.java

#546 
Goal of this pr is to load both custom and system truststore while creating the SSL context.

Load system truststore in the SSL Context

---

build.gradle

Bump legacy version to 1.3.7 for release

Release symphony-legacy-bdk-1.3.7

---

build.gradle

[PLAT-11211](https://perzoinc.atlassian.net/browse/PLAT-11211)
After releasing 2.2.0, project version is bumped to 2.3.0 snapshot for the next release.

PLAT-11211 bump project version to next release snapshot 2.3.0

---

symphony-bdk-bom/build.gradle

#557 
Backport of #558 : override of jersey version in the bom

#557 : Backport of #558 (override of jersey version in the bom)

---

build.gradle

[PLAT-11211](https://perzoinc.atlassian.net/browse/PLAT-11208)
Bumped project version to 2.2.1 after bug fix in #559

PLAT-11211: bump project version to 2.2.1 after bug fix

---

symphony-bdk-bom/build.gradle
symphony-bdk-core/build.gradle
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle
symphony-bdk-template/symphony-bdk-template-handlebars/build.gradle

Upgraded outdated dependencies to their latest minor versions

General dependencies upgrade

---

docs/migration.md

Renaming BDK to SDK when talking about the legacy SDK.

BDK to SDK renaming

---

build.gradle
docs/migration.md
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/AuthenticatorFactory.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorCertImpl.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorRsaImpl.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/StreamService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorCertImplTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorRsaImplTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/stream/StreamServiceTest.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkCoreConfig.java

Backport commits for release 2.4.1

Prepare release 2.4.1

---

symphony-bdk-bom/build.gradle
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle

Just to keep to date with the latest version

Upgrade Spring Boot to 2.6.1

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/MockApiClient.java

Closes https://github.com/finos/symphony-bdk-java/issues/598
Adding support for the Suspend User Account v1 public API  (https://developers.symphony.com/restapi/reference#suspend-user-v1)

Support user suspension API

---

build.gradle

Release PR https://github.com/finos/symphony-bdk-java/pull/604 
Release the fix of vulnerabilities.

Bumped legacy version to 1.3.8

---

build.gradle
symphony-bdk-bom/build.gradle
symphony-bdk-core/build.gradle
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/MockApiClient.java
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle

Backport of the suspension API and dependency upgrades

Prepare 2.4.3 release

---

build.gradle

PLAT-11675
Bumped version to 2.5.0 to release new version

Release 2.5.0.RC1

---

build.gradle

PLAT-11675
Bumped version to 2.5.0-SNAPSHOT after creation of 2.5-rc branch

Bumped version to 2.5.0-SNAPSHOT after creation of 2.5-rc branch

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/CursorBasedPaginatedApi.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/CursorBasedPaginatedService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/OffsetBasedPaginatedApi.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/OffsetBasedPaginatedService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/PaginatedService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/pagination/model/CursorPaginatedPayload.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/signal/SignalService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/StreamService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/arch/CoreArchitectureTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/pagination/CursorBasedPaginatedServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/pagination/OffsetBasedPaginatedServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/pagination/TestCursorPaginatedPayload.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-core/src/test/resources/audit_trail/audit_trail_initiator_list_v1_pagination.json
symphony-bdk-examples/bdk-group-example/src/main/java/com/symphony/bdk/examples/GroupExtensionExample.java
symphony-bdk-examples/bdk-spring-boot-example/src/main/java/com/symphony/bdk/examples/spring/api/GroupApi.java
symphony-bdk-extensions/symphony-group-extension/build.gradle
symphony-bdk-extensions/symphony-group-extension/src/main/java/com/symphony/bdk/ext/group/SymphonyGroupService.java
symphony-bdk-extensions/symphony-group-extension/src/main/java/com/symphony/bdk/ext/group/auth/OAuthSession.java
symphony-bdk-extensions/symphony-group-extension/src/test/java/com/symphony/bdk/ext/group/SymphonyGroupBdkExtensionTest.java
symphony-bdk-extensions/symphony-group-extension/src/test/java/com/symphony/bdk/ext/group/SymphonyGroupExtensionArchitectureTest.java
symphony-bdk-extensions/symphony-group-extension/src/test/java/com/symphony/bdk/ext/group/SymphonyGroupServiceTest.java
symphony-bdk-extensions/symphony-group-extension/src/test/java/com/symphony/bdk/ext/group/TestApiClient.java
symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/Pair.java

PLAT-11729
Simplified interface of two endpoints of Groups API
Added unit tests and coverage checks.
Moved three endpoints from UserService to cursor-based pagination:
* listAllAuditTrail
* listAllUserFollowers
* listAllUserFollowing

Polish groups

---

symphony-bdk-examples/bdk-multi-instances-example/build.gradle

Upgrade hazelcast version in examples

---

buildSrc/build.gradle
buildSrc/src/main/groovy/bdk.java-common-conventions.gradle
symphony-bdk-bom/build.gradle
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle

Mainly Spring Boot 2.6.1 -> 2.6.3
Also introduce the versions plugin so we can check available upgrades
with: gradle dependencyUpdates

Upgrade dependencies

---

symphony-bdk-examples/bdk-multi-instances-example/build.gradle

Upgrade Hazelcast

---

buildSrc/.snyk
buildSrc/build.gradle
symphony-bdk-bom/build.gradle
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle

Also upgrade plugins and try to avoid Snyk reports on build only
dependencies.

Upgrade dependencies (Spring Boot 2.6.4)

---

symphony-bdk-bom/build.gradle

To address https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698

Upgrade Jackson to 2.13.2

---

symphony-bdk-bom/build.gradle
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle

Upgrading some of the Java BDK dependencies

Upgrading dependencies

---

build.gradle

Prepared release 2.7.0

---

build.gradle

Bumped to 2.8.0-SNAPSHOT after creation of 2.7-rc branch

Bumped to 2.8.0-SNAPSHOT after creation of 2.7-rc branch

---

docs/datafeed.md

Fixed links in markdown documentation datafeed.md

Fixed links in markdown documentation datafeed.md

---

docs/activity-api.md
docs/application.md
docs/authentication.md
docs/connection.md
docs/datafeed.md
docs/disclaimer.md
docs/health.md
docs/index.md
docs/message.md
docs/presence.md
docs/signal.md
docs/stream.md
docs/user.md

Added missing services in the documentation

Added missing services in the documentation

---

symphony-bdk-core/build.gradle
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/model/Message.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/model/MessageTest.java
symphony-bdk-core/src/test/resources/message/update_message.json
symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/MessageUpdateExampleMain.java

- Update Symphony APIs spec version
- Add silent flag support according to the new spec.
When silent is true, the new updated message is marked as read, otherwise is unread.
True is the default value.

Add silent message update support

---

docs/migration.md

Fix link to API specs

---

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/OboMessageService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/OboStreamService.java
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/StreamService.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/stream/StreamServiceTest.java

Based on https://developers.symphony.com/restapi/reference/obo-enabled-endpoints, Some apis that are OBO enabled were missing in OboServices interfaces.
We added them in this PR.
Fixed some warnings as well.

Added missing OBO services

---

build.gradle

Bumped version to 2.9.0 in order to release

Bumped version to 2.9.0 in order to release

---

build.gradle

Bumped SNAPSHOT version

---

symphony-bdk-core/build.gradle
symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatahoseLoopImpl.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatahoseLoopTest.java

Move code generator to OpenApi 3.0

---

build.gradle

Bumped version to 2.10.0 for new release

Bumped version to 2.10.0 for new release

---

build.gradle

Bumped main branch version to 2.11.0-SNAPSHOT after having released 2.10.0

Bump Snapshot version to 2.11.0-SNAPSHOT

---

.github/workflows/build.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/release.yml
docs/message.md
symphony-bdk-bom/build.gradle
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractOboAuthenticatorTest.java
symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AuthenticationRetryTest.java
symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/TemplateExampleMain.java

- Upgrade github checkout action version.
- Upgrade spring boot version
- Add inline template doc and sample code

Upgrade github workflow action versions and dependencies version 

---

allow-list.xml
build.gradle
docs/index.md
docs/test.md
settings.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/src/main/java/com/symphony/bdk/examples/spring/GifFormActivity.java
symphony-bdk-examples/bdk-spring-boot-example/src/test/java/com/symphony/bdk/examples/spring/SampleSpringAppIntegrationTest.java
symphony-bdk-test/build.gradle
symphony-bdk-test/symphony-bdk-test-jupiter/build.gradle
symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/SymphonyBdkTestContext.java
symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/SymphonyBdkTestMock.java
symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/SymphonyBdkTestUtils.java
symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/mockito/MessageMatchers.java
symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/mockito/matcher/MessageContains.java
symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/mockito/matcher/MessageEquals.java
symphony-bdk-test/symphony-bdk-test-spring-boot/build.gradle
symphony-bdk-test/symphony-bdk-test-spring-boot/src/main/java/com/symphony/bdk/test/BdkSpringTestProperties.java
symphony-bdk-test/symphony-bdk-test-spring-boot/src/main/java/com/symphony/bdk/test/SymphonyBdkSpringTestConfig.java
symphony-bdk-test/symphony-bdk-test-spring-boot/src/main/java/com/symphony/bdk/test/spring/annotation/SymphonyBdkSpringBootTest.java

BDK provided a new test module, which help BDK Bot developers easily create integration tests to validate their Bot application features.
This commit provided the test module for springboot based bot application only, the java based solution will come up soon.

Add symphony-bdk-test module

---

allow-list.xml
symphony-bdk-bom/build.gradle
symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle
symphony-bdk-examples/bdk-spring-boot-example/build.gradle
symphony-bdk-test/symphony-bdk-test-jupiter/build.gradle

Align jupiter api version

---

allow-list.xml
symphony-bdk-test/symphony-bdk-test-spring-boot/build.gradle

Add spring web dependency in test module

---

build.gradle

Bump version to prepare releasing Java BDK 2.13.0

Release BDK 2.13.0

---

build.gradle

Bump snapshot version 2.14.0-SNAPSHOT on main branch after releasing 2.13.0

Bump snapshot version 2.14.0-SNAPSHOT on main branch

---

docs/spring-boot/core-starter.md
symphony-bdk-examples/bdk-spring-boot-example/src/main/java/com/symphony/bdk/examples/spring/RealTimeEventsDemo.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/events/RealTimeEventsAsyncTestListener.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/events/RealTimeEventsTestListener.java

update doc and the code examples to reflect the changes done in the PR https://github.com/finos/symphony-bdk-java/pull/748.

Update doc and code example on RealTimeEvent listener

---

allow-list.xml
symphony-bdk-bom/build.gradle

Update springboot to 2.7.11

---

allow-list.xml
symphony-bdk-bom/build.gradle
symphony-bdk-examples/bdk-multi-instances-example/build.gradle

Upgrade SpringBoot version

---

build.gradle

Bump BDK major version

---

build.gradle

Release BDK 3.0.0-Alpha

---

docs/activity-api.md
docs/migration.md
docs/spring-boot/core-starter.md
docs/test.md

Fix docs merge from #772

---

symphony-bdk-bom/build.gradle

https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONDATAFORMAT-5829117

Fix CVE-2023-3894

---

buildSrc/src/main/groovy/bdk.java-common-conventions.gradle

Use dot in module name

---

symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkActivityConfig.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkDatafeedConfig.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkDatahoseConfig.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkServiceConfig.java
symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/service/BotInfoService.java

Introduce BotInfoService to provide cached bot session info

Introduce BotInfoService

---

docs/application.md
docs/connection.md
docs/disclaimer.md
docs/health.md
docs/message.md
docs/presence.md

The Symphony Rest API links are out of date, this PR updated the links to 
the latest.

Fix Symphony REST API doc links
