pom.xml
By default, windows does not have gpg.exe and this step is not needed for building locally and run locally. Maven build should be self contained and be able to build without manual adjustments.
=> Skip maven-gpg-plugin for windows because this is not needed for local build

pom.xml, src/main/java/authentication/SymBotAuth.java, src/main/java/clients/SymBotClient.java, src/main/java/clients/symphony/api/MessagesClient.java
Apply proxy settings to both agentClient and kmAuthClient when using config.json.
I also upgraded pom.xml to SNAPSHOT.
=> SymBotAuth.kmAuthClient doesn't use proxy settings

src/main/java/clients/symphony/api/MessagesClient.java
Fixed sendMessage when appendTags is false so that message is not null
Above also fixed the forwardMessage functionality.
Created new function sendTaggedMessage to send messages that already have messageML tag or PresentationML Tag so we don't append <messageML>
=> MessagesClient fixes:

src/main/java/clients/SymBotClient.java, src/main/java/clients/symphony/api/UsersClient.java, src/main/java/clients/symphony/api/constants/PodConstants.java
Added CONSTANT GETSESSIONUSER for v2/sessioninfo
Added function getSessionUser to UsersClient to call v2/sessioninfo
Changed SymBotClient to use getSessionUser instead of getUserFromEmail
Using botEmailAddress in config file can result in the bot processing its own messages when they come through the datafeed when user provides wrong email or no email.
Using sessioninfo guarantees to get the info of the bot
=> No longer use botEmailAddress to get userId of bot

src/main/java/model/StreamInfo.java, src/main/java/model/StreamType.java, src/main/java/model/StreamTypes.java
This pull request contains a fix on StreamInfo.
The API is sending an object on payload, not a string. In order to make the things easier I created an enumerator to be used on comparisons.
=> fix of StreamInfo

src/main/java/clients/symphony/api/AdminClient.java
The payload of https://rest-api.symphony.com/v1.53.1/reference#get-user-v2 must be parsed by AdminUserInfo.
=> Changing type from UserInfo to AdminUserInfo on AdminClient

src/main/java/model/Password.java
When trying to call `createUser(...)`got the following response : 
```
Unrecognized field "description" (class com.symphony.api.pod.model.Password), not marked as ignorable (4 known properties: "khPassword", "khSalt", "hSalt", "hPassword"])
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@23c55fb9; line: 1, column: 507] (through reference chain: com.symphony.api.pod.model.V2UserCreate["password"]->com.symphony.api.pod.model.Password["description"])
```
This is because the Password POJO contains a **description** field that the pod does not expect.
This PR removes the field.
=> Removed non existing 'description' field from Password class

src/main/java/services/DatafeedEventsService.java
The "exponential" backoff implemented in release `1.0.41` does not allow a maximum backoff duration.
In the `DatafeedEventsService`, we introduced a new constant called `MAX_BACKOFF_TIME` fixed to 5 minutes. If this value is reached, this means that the bot will retry to read or recreate the Datafeed every 5 minutes instead of a potentially unlimited time like it was before.
=> PLAT-8646 Added maximum backoff duration

src/main/java/clients/symphony/api/StreamsClient.java, src/test/java/it/clients/symphony/api/StreamsClientTest.java
Related endpoint : [#list-user-streams](https://developers.symphony.com/restapi/reference#list-user-streams)
When using the `StreamsClient.getUserStreams` function to list the user streams, there is no provision to allow the user to pass the `skip` or `limit` parameter, making the function limited to returning the 50 first rooms.
Prototype of the existing `getUserStreams(List<String>, boolean)` has been preserved for backward compatibility purpose. An additional method has been introduced including the `limit` and `skip` parameters : 
```java
public List<StreamListItem> getUserStreams(List<String>, boolean, int skip, int limit);
```
This method also checks that those parameters are not lower than 0.
=> PLAT-8645 Added missing params (skip and limit) to streams list

src/main/java/clients/symphony/api/StreamsClient.java, src/main/java/services/DatafeedEventsService.java
The Datafeed loop has failed because of an unknown exception has happened : `SocketTimeoutException`. 
The `ProcessingException` and the `SymClientException` that were previously caught have been replaced `Exception` to make sure that the error handling will be processed for any kind of exception.
=> PLAT-8662 Enhanced exception handling in DatafeedEventsService

src/main/java/utils/HttpClientBuilderHelper.java, src/main/java/utils/jersey/NoCacheFeature.java
Added Cache-Control no-cache to all API calls to avoid the sessionToken to be cached.
Opened in favour of https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/pull/91
=> PLAT-8660 Set Cache-Control header value to no-cache

README.md, src/main/java/configuration/SymConfig.java, src/main/java/utils/DataProvider.java
Bug details on https://perzoinc.atlassian.net/browse/PLAT-9037
I'm adding the 'quickws' to be accepted as a valid URI scheme on Java SDK implementation of IDataProvider's validateURI method.
=> PLAT-9037 Adding 'quickws' to be accepted as a valid uri scheme

README.md, pom.xml, src/lombok.config, src/main/java/authentication/ISymAuth.java, src/main/java/authentication/SymBotRSAAuth.java, src/main/java/clients/SymBotClient.java, src/main/java/clients/symphony/api/HealthcheckClient.java, src/main/java/configuration/RetryConfiguration.java, src/main/java/configuration/SymConfig.java, src/main/java/configuration/SymLoadBalancedConfig.java, src/main/java/exceptions/AuthenticationException.java, src/main/java/internal/FileHelper.java, src/main/java/internal/jersey/JerseyHelper.java, src/main/java/internal/jersey/NoCacheFeature.java, src/main/java/utils/HttpClientBuilderHelper.java, src/main/java/utils/JwtHelper.java, src/test/java/internal/FileHelperTest.java, src/test/java/it/authentication/SymBotRSAAuthTest.java, src/test/java/it/commons/BotTest.java, src/test/resources/bot-config.json, src/test/resources/log4j.properties
A customer faced some random troubles with custom truststore configuration. I discovered that this problem was caused by the multi-threaded calls when authenticating a service account with RSA. 
This PR completely refactor the way that RSA authentication is performed by the SDK. I also introduced `resilience4j` as an experimental library for retries. It is also possible to configure the exponential backoff through `config.json` : 
```json
{
"retry": {
"maxAttempts": 10,
"initialIntervalMillis": 500,
"multiplier": 1.5
}
}
```
=> SDK-75 Fixed random SSL issues for RSA authentication

src/main/java/clients/SymOBOClient.java, src/main/java/utils/HttpClientBuilderHelper.java, src/test/java/it/clients/SymBotOBOClientTest.java
With the legacy caching strategy using Singleton pattern, we cannot instantiate different SymOBOClient with different passed user auth.
My solution is, instead of using Singleton, I will use Flyweight pattern to init SymOBOClient by using a HashMap to store all instantiated SymOBOClient referred by keys which are the passed user auth.
=> SDK-80 Changing caching strategy of SymOBOClient

pom.xml, src/main/java/authentication/jwt/AuthenticationFilter.java, src/test/java/it/authentication/jwt/AuthenticationFilterTest.java
- Check if authorization headers of request is null or not to avoid NullPointerException when doing a substring.
- Add unittest for AuthenticationFilter
=> SDK-81 Handle null authorization header

.github/CODEOWNERS, src/main/java/clients/symphony/api/APIClient.java, src/test/java/it/clients/symphony/api/StreamsClientTest.java
The issue in ticket SDK-90 comes from the 401 error returned with no content-type in headers.
`ClientError error = response.readEntity(ClientError.class);`
So, instead using Json parser to `readEntity` as `ClientError` object, we will content of response as a String then parse it with Jackson.
```
String errorString = response.readEntity(String.class);
ObjectMapper mapper = new ObjectMapper();
ClientError error;
try {
error = mapper.readValue(errorString, ClientError.class);
} catch (JsonProcessingException e) {
throw new APIClientErrorException(e.getMessage());
}
```
=> SDK-90: Handle null content-type 401 error response

src/test/java/it/configuration/SymConfigLoaderTest.java
This is to have file separator '\' on Windows being escaped properly in unit tests
=> SDK-99: make tests SymConfigLoaderTest compatible with windows

src/main/java/clients/SymBotClient.java, src/main/java/clients/symphony/api/DatafeedClient.java, src/main/java/clients/symphony/api/DatafeedClientV1.java, src/main/java/clients/symphony/api/DatafeedClientV2.java, src/main/java/clients/symphony/api/IDatafeedClient.java, src/main/java/services/AbstractDatafeedEventsService.java, src/test/java/it/clients/symphony/api/DatafeedClientV1Test.java, src/test/java/it/clients/symphony/api/DatafeedClientV2Test.java, src/test/java/services/DatafeedEventsServiceTest.java
Before, the DatafeedClient is under symphony.api package, so moving it
to datafeeds package might break the compatibility of project. That's
why it should be moved out of datafeed package, back to symphony.api.
=> Move DatafeedClient out of datafeeds package

.circleci/config.yml, pom.xml, symphony-bdk-core/pom.xml, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigLoader.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigParser.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/LegacyConfigMapper.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/legacy/model/LegacyRetryConfiguration.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/legacy/model/LegacySymConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/legacy/model/RetryConfiguration.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkBotConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkClientConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkExtAppConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkSSLConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkSslConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/exceptions/BdkConfigException.java
Define new structure for Configuration in 2.0 in BdkConfig.java.
Both of yaml and json formats are supported in 2.0, so Yaml parser
is added for parsing Yaml config
LegacyConfig model for supporting the legacy version of configuration.
Configuration is loaded by BdkConfigLoader in three ways:
- From path of config file: BdkConfigLoader#loadFromFile
- From inputstream: BdkConfigLoader#loadFromInputStream
- From classpath: BdkConfigLoader#loadFromClasspath
Set minimum code coverage score: 0.9
=> Add Configuration features for BDK 2.0

.circleci/config.yml, pom.xml, symphony-bdk-core/pom.xml, symphony-bdk-legacy/symphony-api-client-java/pom.xml
I activated code coverage checks on both of BDK 2.0 and Legacy SDK.
For BDK, I temporarily exclude two files: BdkCore.class and JwtHelper.class because there is now no unit test on these two files (the exclusion should be removed when the PR of @symphony-thibault is finished with the code coverage >90%)
=> Activate code coverage check on BDK 2.0 and legacy

symphony-bdk-legacy/symphony-api-client-java/src/main/java/clients/symphony/api/DatafeedClientV2.java, symphony-bdk-legacy/symphony-api-client-java/src/main/java/services/DatafeedEventsServiceV2.java, symphony-bdk-legacy/symphony-api-client-java/src/test/java/services/DatafeedEventsServiceTest.java
Once reading a datafeed throws an APIClientException, it means that
the datafeed is faulty. Before, this datafeed is automatically removed
after being read but now it's not removed anymore. Therefore, the
faulty datafeed should be deleted manually after the exception is thrown.
=> APP-2898: Fix exception handling when reading a faulty datafeed

src/main/java/model/Attachment.java
- [Jira Ticket](https://perzoinc.atlassian.net/browse/CES-1719)
- We want to make use of the thumbnail of the image attachment.
- We can see that the agent is already sending that inside the attachment object in the `images` field.
- This field was missing in the `Attachment` class. So, we have added it.
=> CES-1719: Added the images field to Attachment

docs/configuration.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigLoader.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkClientConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkConfig.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/ApiClientFactoryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigLoaderTest.java, symphony-bdk-core/src/test/resources/config/config_client_global.yaml, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/DatafeedExampleMain.java, symphony-bdk-examples/bdk-core-examples/src/main/resources/enhanced_config.yaml
- 4 properties added to BdkConfig to specify the global configurations for host,
port, scheme and context. These properties can be used if they are not configured
in the api client configuration.
- Version of configuration file is also removed because it seems useless.
- Unittest updated
- Documentation updated
=> APP-3000: Simplified configuration when the configuration of api client is the same

docs/activity.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/SlashCommand.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/model/ActivityType.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/TestCommandActivity.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/SlashCommandTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/form/TestFormReplyActivity.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigLoaderTest.java, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/activity/Example.java, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/activity/GifCommand.java, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/activity/GifFormReplyActivity.java, symphony-bdk-examples/bdk-core-examples/src/main/resources/hello.mml.xml, symphony-bdk-legacy/symphony-bdk-bot-sdk-java/pom.xml
Reference documentation for the new Activity API. Added to file [`./doc/activity.md`](https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/blob/2b7fdba88c27782485a032a7c3e8500c5b29cdbd/docs/activity.md)
=> APP-3031 Activity API Documentation

build.gradle, jenkins/Jenkinsfile-release, jenkins/Jenkinsfile-release-legacy, symphony-bdk-bom/build.gradle, symphony-bdk-legacy/build.gradle
The nexus plugin we were using was not supporting BOM files. We ended up
using the maven-publish plugin (and kept the nexus staging plugin to
close and release the staging repository).
By default the repository URL is the Nexus staging one.
The POM definition is shared at top level with a closure.
Also applied this to legacy project.
[APP-3106](https://perzoinc.atlassian.net/browse/APP-3106)
=> APP-3106: Publish BOM when releasing

symphony-bdk-legacy/symphony-api-client-java/src/main/java/model/OutboundMessage.java
[APP-3103](https://perzoinc.atlassian.net/browse/APP-3103)
There are two setters setContentAttachment in OutboundMessage which can lead to
ambigous reference error while deserializing with Jackson. Associated
OutboundMessage#setContentAttachment(ContentAttachment) with @JsonIgnore to
prevent Jackson use this setter to deserialize
=> APP-3103: Add @JsonIgnore to the OutboundMessage#setContentAttachment(ContentAttachment)

symphony-bdk-template/symphony-bdk-template-handlebars/src/main/java/com/symphony/bdk/template/handlebars/HandlebarsEngine.java, symphony-bdk-template/symphony-bdk-template-handlebars/src/test/java/com/symphony/bdk/template/handlebars/HandlebarsEngineTest.java, symphony-bdk-template/symphony-bdk-template-handlebars/src/test/resources/base.hbs, symphony-bdk-template/symphony-bdk-template-handlebars/src/test/resources/home.hbs
[APP-3120](https://perzoinc.atlassian.net/browse/APP-3120)
By default, Handlebars automatically appends `.hbs` extension to template names. This behaviour is not consistent with with existing Freemarker implementation.  
N/A
=> APP-3120 Handlebars does not automatically append .hbs extension to template name

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/build.gradle, symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/resources/application-base.properties
[APP-3187](https://perzoinc.atlassian.net/browse/APP-3187)
The legacy strategy for expanding property (`@symphony.apiclient.version@`) only works with
Maven project. Since we decided to use gradle instead, this expansion haven't worked anymore.
That's why we have to update the properties file with the gradle auto property expansion.
More details: https://docs.spring.io/spring-boot/docs/1.4.x/reference/html/howto-properties-and-configuration.html#howto-automatic-expansion-gradle
=> APP-3187: Spring boot auto property expansion strategy for gradle project

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/symphony/DatafeedClientImpl.java
[APP-3199](https://perzoinc.atlassian.net/browse/APP-3199)
Add a way to enable/disable datafeed polling in legacy BDK
N/A
=> add option to enable/disable datafeed polling

symphony-bdk-legacy/build.gradle, symphony-bdk-legacy/symphony-bdk-bot-sdk-java/build.gradle
Versions for Spring Boot Actuator and Micrometer were not defined in the
constraints. While it was not breaking the build because transitive
dependencies were used, it was breaking the POM generation, leaving the
versions empty.
A project using the SDK as a dependency would then not get the
transitive dependencies automatically.
(cherry picked from commit 8e231d4e24b5b6264d8afb15540b3771f6ab082f)
=> Generated POM for legacy bot SDK is missing versions

symphony-bdk-core/src/main/java/com/symphony/bdk/core/OboServices.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/ServiceFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/signal/OboSignalService.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/signal/SignalService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/OboServicesTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/ServiceFactoryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/SymphonyBdkTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/signal/SignalServiceTest.java, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/ServiceExampleMain.java, symphony-bdk-legacy/build.gradle, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkServiceConfig.java
[APP-3142](https://perzoinc.atlassian.net/browse/APP-3142)
OboSignalService to enable the Obo service for SignalService.
SignalService exposing all endpoints relate to signals information.
Entry to get SignalService from SymphonyBdk entry point.
PaginatedService for SignalService#listSignals and SignalService#subscribers
=> APP-3142: Adding SignalService feature

docs/message.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/OboMessageService.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/model/Message.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/model/MessageTest.java
[APP-3178](https://perzoinc.atlassian.net/browse/APP-3178)
- methods `MessageService#send(V4Stream, String)` and `MessageService#send(String, String)` are not deprecated anymore
- auto append `<messageML/>` tag to message content if not set
N/A
=> APP-3178 Removed deprecation on MessageService#send(V4Stream|String, String), auto append <messageML> tag to message content if not set

docs/configuration.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/ApiClientFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/loadbalancing/LoadBalancedApiClient.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/loadbalancing/LoadBalancingStrategyFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/legacy/LegacyConfigMapper.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkAgentConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/ApiClientFactoryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/loadbalancing/DatafeedLoadBalancedApiClientTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/loadbalancing/LoadBalancingStrategyTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/client/loadbalancing/RegularLoadBalancedApiClientTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigLoaderTest.java, symphony-bdk-core/src/test/resources/config/config_lb.yaml, symphony-bdk-core/src/test/resources/config/config_lb_external.yaml, symphony-bdk-core/src/test/resources/config/config_lb_invalid_mode.yaml, symphony-bdk-core/src/test/resources/config/config_lb_no_stickiness.yaml, symphony-bdk-core/src/test/resources/config/config_lb_round_robin.yaml, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/SymphonyBdkAutoConfigurationTest.java
[APP-3137](https://perzoinc.atlassian.net/browse/APP-3137)
Moved configuration field from agents to agent.loadBalancing
=> APP-3137: Moved configuration field from agents to agent.loadBalancing

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/commons/MDCTaskDecoratorTest.java
[166](https://perzoinc.atlassian.net/browse/SDK-166?atlOrigin=eyJpIjoiOTM2ZjlhZjViNjI3NGY4MGI2MWRiZjMxNjYwNGMzYjciLCJwIjoiaiJ9)
=> SDK-166 Java-BDK: Create test coverage for MDCTaskDecorator

symphony-bdk-core/src/main/java/com/symphony/bdk/core/util/ServiceLookup.java, symphony-bdk-template/symphony-bdk-template-api/src/main/java/com/symphony/bdk/template/api/TemplateEngine.java
[APP-3113](https://perzoinc.atlassian.net/browse/APP-3113)
Instead of a warn log, an exception is thrown in `ServiceLookup.singleService(Class<?>)`.
=> APP-3113: Throw exception if multiple implementations found in classpath for http-api and template-api

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/extapp/authentication/AppAuthController.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/auth/CircleOfTrustController.java
[APP-3271](https://perzoinc.atlassian.net/browse/APP-3271)
By default, the SameSite flag will be set automatically to 'Lax' and
will be blocked because it comes from a cross-site response. Setting
it to None to make it available for store in browser cookies.
=> APP-3271: Set SameSite flag equals None to jwtCookies

symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/events/RealTimeEvent.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/events/RealTimeEventListenerTest.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/events/RealTimeEventsDispatcherTest.java
[APP-3280](https://perzoinc.atlassian.net/browse/APP-3280)
Spring was not differentiating between an @EventListener on RealTimeEvent<T> and RealTimeEvent<U>.
RealTimeEvent now implements ResolvableTypeProvider, based on example https://github.com/altfatterz/application-events-with-spring/blob/master/src/main/java/com/zoltanaltfatter/events/generics/GenericEventsExample.java
Tested locally on devx3.
=> APP-3280: Fixed event listeners on RealTimeEvent<T> with different param types

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/lib/templating/TemplateServiceTest.java, symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/resources/templates/testTemplate.hbs
[SDK-168](https://perzoinc.atlassian.net/browse/SDK-168)
Added coverage for TemplateServiceImpl.
=> SDK-168 Java BDK: Create test coverage for com.symphony.bdk.bot.sdk.lib.templating.TemplateServiceImpl

.circleci/config.yml
[APP-3296](https://perzoinc.atlassian.net/browse/APP-3296)
The build-legacy is currently running in the regular build step, and it looks like it was not the intent.
=> APP-3296 Make BDK CI steps more accurate

docs/spring-boot/core-starter.md, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkDatafeedConfig.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/SymphonyBdkAutoConfigurationTest.java
[APP-3203](https://perzoinc.atlassian.net/browse/APP-3203)
Made the start of the datafeed loop optional. Enabled by default, can be disabled with property `bdk.datafeed.enabled = false`
FYI In the legacy BDK (see #302) choice was to have property `datafeed.polling.disabled=true` in order to disable the DF loop. I made the choice (can subject to comments and changes) to remove the intermediary `polling` object and put `enabled` instead of `disabled` to avoid using a "negative" property name.
=> APP-3203: Optional start of DF loop in spring boot starter

docs/spring-boot/app-starter.md, docs/tech/production-readiness.md, symphony-bdk-examples/bdk-app-spring-boot-example/src/main/java/com/symphony/bdk/examples/app/spring/HelloController.java, symphony-bdk-examples/bdk-app-spring-boot-example/src/main/resources/application.yaml, symphony-bdk-http/symphony-bdk-http-api/build.gradle, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/ApiClient.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/tracing/DistributedTracingContext.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/tracing/MDCUtils.java, symphony-bdk-http/symphony-bdk-http-api/src/test/java/com/symphony/bdk/http/api/tracing/DistributedTracingContextTest.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientWebClient.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/SymphonyBdkAppAutoConfiguration.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/SymphonyBdkAppProperties.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkExtAppTracingFilterConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/filter/TracingFilter.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/properties/TracingProperties.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/SymphonyBdkAppAutoConfigurationTest.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkExtAppTracingFilterConfigTest.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/filter/TracingFilterTest.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/annotation/SlashAnnotationProcessor.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/service/DatafeedAsyncLauncherService.java
[APP-3125](https://perzoinc.atlassian.net/browse/APP-3125)
Header `X-Trace-Id` is now forwarded to every API call. As well, the value is also set in logger MDC for debugging purpose. 
A `TracingFilter` has been created in `app-starter` to init the `X-Trace-Id` value for each incoming request.
=> APP-3125 Forwarded X-Trace-Id to every API call

symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/jwt/JwtHelper.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/JwtHelperTest.java
[APP-3281](https://perzoinc.atlassian.net/browse/APP-3281)
Some errors were not properly caught during pkcs1 key parsing (e.g. in case of an invalid key) therefore making exception message and stack trace not so obvious to understand.
=> APP-3281: Wrapped exceptions occurring during pkcs1 key parsing in a GeneralSecurityException

symphony-bdk-legacy/symphony-api-client-java/src/main/java/utils/HttpClientBuilderHelper.java, symphony-bdk-legacy/symphony-api-client-java/src/test/java/utils/HttpClientBuilderHelperTest.java
[APP-3351](https://perzoinc.atlassian.net/browse/APP-3351)
Wrong proxy credentials were passed to the KeyManager http client.
=> APP-3351: fixed wrong proxy credentials passed for KM client

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/MessageExampleMain.java
[PLAT-10091](https://perzoinc.atlassian.net/browse/PLAT-10091)
Remove Stream-based pagination for the listMessage endpoints.
Remove broken api for listMessageByTimestamp endpoints.
=> PLAT-10091: Refactor MessageService

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/command/matcher/CommandMatcherBuilderTest.java
[SDK-175](https://perzoinc.atlassian.net/browse/SDK-175)
Added unit test for command.matcher.**CommandMatcherBuilder**.
=> SDK-175: Java SDK: create test coverage for command.matcher.CommandMatcherBuilder

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/symphony/ExtensionAppAuthClientTest.java
[SDK-181](https://perzoinc.atlassian.net/browse/SDK-181)
Added unit test for ExtensionAppAuthClientImpl.
=> SDK-181 Java SDK: create test coverage for sdk.symphony.ExtensionAppAuthClientImpl

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/symphony/MessageClientImplTest.java
[SDK-178](https://perzoinc.atlassian.net/browse/SDK-178?atlOrigin=eyJpIjoiMmZkNzFjNGY0ZjUzNDI5Y2JjYTg1NGFjNzRiNjMxNTMiLCJwIjoiaiJ9)
=> SDK-178 Java BDK: Create test coverage for sdk.symphony.MessageClientImpl

build.gradle, docs/getting-started.md, docs/spring-boot/app-starter.md, docs/spring-boot/core-starter.md, symphony-bdk-bom/build.gradle, symphony-bdk-core/build.gradle, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientWebClientTest.java, symphony-bdk-legacy/build.gradle, symphony-bdk-legacy/symphony-api-client-java/src/main/java/authentication/SymOBOAuth.java, symphony-bdk-legacy/symphony-api-client-java/src/main/java/authentication/SymOBOUserAuth.java
PLAT-10295
Bump version to 2.0.0-SNAPSHOT (will be 2.0.0-RC1 in the RC branch)
Update documentation to use 2.0.0 as we expect most of of the readers to
use this version forward.
Use a branch version for Swagger spec for stability and reproductible
builds.
Upgrade dependencies (Spring Boot to 2.4.1 and others)
It caused one of the test to fail because the content type header is a
bit different, relaxed the test to pass.
Next will be the creation on a 2.0-rc branch.
Upcoming PR on generator.
=> PLAT-10295: Prepare 2.0.0 release

symphony-bdk-legacy/build.gradle
PLAT-10294
This version forces UTF-8 to be used when parsing messageML.
If the bot was not running with UTF-8 encoding special characters
handling could fail when reading messages.
https://github.com/symphonyoss/messageml-utils/issues/229
- [N/A] Unit tests updated or added
=> PLAT-10294: Upgrade messageml lib to 0.9.64

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/RealTimeEventListener.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/RealTimeEventType.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1Test.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java
[PLAT-10113](https://perzoinc.atlassian.net/browse/PLAT-10113)
Add method to RealtimeEventListener to handle self-created events
=> PLAT-10113: Add method to RealtimeEventListener to handle self-created events

build.gradle, docs/spring-boot/app-starter.md, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkExtAppSecurityConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/properties/CorsProperties.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkExtAppSecurityConfigTest.java
[PLAT-10338](https://perzoinc.atlassian.net/browse/PLAT-10338)
Renamed CORS properties: 
- allowed-origin → allowed-origin**s**
- allowed-credentials → **allow**-credentials
A `WARN` message is displayed at application startup if old properties are still configured in `application.yaml`. 
We initially made 2 small mistakes when naming our CORS properties compared to how they are named in Spring Boot: see [CorsProperties](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html).
=> PLAT-10338 Rename wrong CORS properties names

docs/spring-boot/app-starter.md, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkExtAppSecurityConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/properties/CorsProperties.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkExtAppSecurityConfigTest.java
> Cherry-picked from #404
[PLAT-10338](https://perzoinc.atlassian.net/browse/PLAT-10338)
Renamed CORS properties: 
- allowed-origin → allowed-origin**s**
- allowed-credentials → **allow**-credentials
A `WARN` message is displayed at application startup if old properties are still configured in `application.yaml`. 
We initially made 2 small mistakes when naming our CORS properties compared to how they are named in Spring Boot: see [CorsProperties](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html).
=> PLAT-10338 Rename wrong CORS properties names (2.0-rc backport)

docs/configuration.md, docs/spring-boot/app-starter.md, symphony-bdk-bom/build.gradle, symphony-bdk-core/build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/BdkConfigParser.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigParserTest.java, symphony-bdk-core/src/test/resources/config/config_lb_properties.yaml, symphony-bdk-core/src/test/resources/config/config_properties.json, symphony-bdk-core/src/test/resources/config/config_properties.yaml, symphony-bdk-core/src/test/resources/config/config_recursive_props.json
PLAT-10150
Before parsing the json or yaml, we apply [StringSubstitutor.replaceSystemProperties](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringSubstitutor.html#replaceSystemProperties(java.lang.Object)).
=> PLAT-10150: Support of system properties in configuration

docs/configuration.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/AuthenticatorFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkCertificateConfig.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/AuthenticatorFactoryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigTest.java
PLAT-10151
Support of classpath resource paths in configuration for certificates and truststore.
=> PLAT-10151: Support of classpath paths in configuration

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/model/ActivityType.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/room/UserJoinedRoomActivity.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/room/UserJoinedRoomContext.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/util/RealTimeEventsBinder.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/room/TestUserJoinedRoomActivity.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/room/UserJoinedRoomActivityTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/util/RealTimeEventsBinderTest.java
[PLAT-10112](https://perzoinc.atlassian.net/browse/PLAT-10112)
UserJoinedRoomActivity class created to reacting to room created real-time events.
Created class UserJoinedRoomContext to be handled by the UserJoinedRoomActivity containing the information of the room Id and the user Id.
Created method RealTimeEventsBinder#bindOnUserJoinedRoom to bind the "onUserJoinedRoom" real-time event to a target method.
Added Unittest.
=> PLAT-10112: Create Activity class reacting to user joined room event.

symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/annotation/SlashAnnotationProcessor.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkActivityConfig.java
PLAT-10360
When Spring integration is used we could see messages such as:
2021-01-08 11:40:18.767  INFO 86263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'com.symphony.bdk.spring.config.BdkActivityConfig' of type [com.symphony.bdk.spring.config.BdkActivityConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
during startup.
This was caused because the BeanPostProcessor for slash commands has a
dependency on ActivityRegistry. This is a bean that has other beans as
dependencies too. So the processor is created after a few beans has
already been created and Spring warns us that those beans might not have
been processed.
We remove this dependency by not injecting the activity registry during
the …
=> PLAT-10360: Remove Spring warning during startup

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/sse/SseSubscriberTest.java
[SDK-190](https://perzoinc.atlassian.net/browse/SDK-190)
Added unit test for SseSubscriber
=> SDK-190 Java SDK: create coverage for sse.SseSubscriber

symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/sse/SsePublisher.java, symphony-bdk-legacy/symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/sse/SsePublisherTest.java
[SDK-188](https://perzoinc.atlassian.net/browse/SDK-188?atlOrigin=eyJpIjoiY2JhMTlhZjQ0MTdhNGFhODkyMWZlZjlkMTVjZThmZTAiLCJwIjoiaiJ9)
When I tested the method `addSubscriber`, I got a `NullPointerException` because this method used the field private `ConcurrentHashMap<String, List<SseSubscriber>> subscribers` but there was no setter for this field. It was set only in the method `register()` which is private.
So I made a protected setter for this field
=> SDK-188 Java BDK: Create coverage for sse.SsePublisher

.circleci/config.yml, build.gradle, buildSrc/build.gradle, buildSrc/src/main/groovy/bdk.java-common-conventions.gradle, buildSrc/src/main/groovy/bdk.java-library-conventions.gradle, buildSrc/src/main/groovy/bdk.java-publish-conventions.gradle, symphony-bdk-bom/build.gradle, symphony-bdk-core/build.gradle, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-core-examples/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle, symphony-bdk-http/symphony-bdk-http-api/build.gradle, symphony-bdk-http/symphony-bdk-http-jersey2/build.gradle, symphony-bdk-http/symphony-bdk-http-webclient/build.gradle, symphony-bdk-legacy/.snyk, symphony-bdk-legacy/build.gradle, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/build.gradle, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/build.gradle, symphony-bdk-template/symphony-bdk-template-api/build.gradle, symphony-bdk-template/symphony-bdk-template-freemarker/build.gradle, symphony-bdk-template/symphony-bdk-template-handlebars/build.gradle
PLAT-10379
Two main changes described below.
I have not tested a release (a bit complex) so there a is risk for the next release that we discover issues only when actually releasing
---
CircleCI configuration for Snyk
We want to run Snyk only master branch to avoid exposing the SNYK_TOKEN
on any PR (as the project is OSS).
A separate job is defined for that purpose using the Gradle Snyk plugin.
The SNYK_TOKEN is set in a context that can be reused across DevX jobs.
Also configure an exclusion for log4j that we won't fix.
---
Run Snyk with Gradle + cleaner build …
The Gradle Snyk plugin is used, it adds 2 tasks:
- snyk-test
- snyk-monitor
The task is only configured at the root level and with the option to
look at subproject (it is faster than running it for each project).
Most of the …
=> PLAT-10379: Run Snyk instead of Github integration

symphony-bdk-core/build.gradle, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/JwtHelperTest.java
PLAT-10445
We are facing the issue
https://github.com/mapstruct/mapstruct/issues/2215 with the latest
version of IDEA (NPE when building from IDEA), upgrading to latest
version fixes it.
Also make the unit test faster by generating smaller RSA keys (saving a
few seconds).
N/A
- [-] Unit tests updated or added
- [-] Javadoc added or updated
- [-] Updated the documentation in [docs folder](../docs)
=> PLAT-10445: Upgrade Mapstruct to latest version (1.4.1)

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/form/FormReplyContext.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/form/FormReplyActivityTest.java
https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/issues/427 FormReplyActivity throws NPE for unchecked checkboxes
Sending an elements form with a checkbox, leaving it unchecked, then using FormReplyActivity to getFormValue throws a NullPointerException. Expectation: return null or false instead.
- [N/A] Filled properly the description and dependencies, if any
=> #427 FormReplyActivity throws NPE for unchecked checkboxes

symphony-bdk-core/build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/AuthenticationRetry.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecoveryBuilder.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractBotAuthenticatorTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractExtensionAppAuthenticatorTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractOboAuthenticatorTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AuthenticationRetryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/retry/resilience4j/Resilience4jRetryWithRecoveryTest.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientWebClient.java
!!! **Update on last commit** !!!
When a proxy is configured the jersey client is throwing ProcessingException enclosing a ConnectTimeoutException so also in this case I transformed that into a SocketTimeoutException so that we trigger the retry.
https://perzoinc.atlassian.net/browse/PLAT-10110
Depending on the http client used, network issues can throw different kind of exceptions in case of "connection timeout" and "connection refused" :
**Jersey2 client**
- ProcessingException enclosing a ConnectException
- ProcessingException enclosing a SocketTimeoutException
**Webclient**
- WebClientRequestException enclosing a ConnectException
- WebClientRequestException enclosing a ConnectTimeoutException
This is a draft PR to get some feedbacks on my idea of instead of basing the timeout on the …
=> PLAT-10110 Catch exceptions on retry based on ApiClient

symphony-bdk-examples/bdk-multi-instances-example/Dockerfile
Use the image recommended by Snyk that has no known vulnerabilities.
=> Update Docker base image in examples

symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/auth/CircleOfTrustController.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/auth/CircleOfTrustControllerTest.java
Removed Tomcat dependency from the CircleOfTrustController so that lib client can use another embedded server (Undertow for instance). 
Closes https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/issues/439
=> #439 Removed Tomcat dependency from the CircleOfTrustController

docs/configuration.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/ApiClientFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkClientConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkServerConfig.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigLoaderTest.java, symphony-bdk-core/src/test/resources/config/config_client_global.yaml, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientWebClient.java
Closes https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/issues/441
`config.yaml` now allows to configure default headers: 
```yaml
host: acme.symphony.com
defaultHeaders:
Connection: Keep-Alive
Keep-Alive: timeout=5, max=1000
bot:
username: mybot
privateKey:
path: /Users/user.name/.symphony/privatekey.pem
```
=> #441 BDK config allows to configure default headers

symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/HttpClientExampleMain.java, symphony-bdk-http/symphony-bdk-http-api/build.gradle, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/HttpClient.java, symphony-bdk-http/symphony-bdk-http-api/src/test/java/com/symphony/bdk/http/api/HttpClientTest.java
Closes https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/issues/443
The `HttpClient` can now reuse the same `ApiClient` once built using the `HttpClient.Builder`. 
⚠️ This is a breaking change. But we assume that this feature was not used in production yet. 
Usage example: 
```java
final HttpClient httpClient = HttpClient.builder(this::mockedApiClientBuilder)
.basePath("https://localhost:8080")
.header("Connection", "Keep-Alive")
.header("Keep-Alive", "timeout=5, max=1000")
.cookie("foo", "bar")
.build();
final String response = httpClient.path("/api/v1/users")
.header("Authorization", "Bearer AbCdEf123456")
.get(new TypeReference<String>() {});
```
=> #443 Redesigned HttpClient that reuses ApiClient instance

.github/workflows/build.yml, build.gradle, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/HttpClient.java, symphony-bdk-http/symphony-bdk-http-api/src/test/java/com/symphony/bdk/http/api/HttpClientTest.java
Closes https://github.com/finos/symphony-bdk-java/issues/462
`Map` and `List` from class `HttpClient#RequestConfig` were not correctly initialized with default values. This was leading to the NPE detected in https://github.com/finos/symphony-bdk-java/issues/462.
=> #462 Fixed HttpClient NPE when adding query param

.github/workflows/build.yml, docs/configuration.md, docs/datafeed.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkDatafeedConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/config/model/BdkRetryConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RecoveryStrategy.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecovery.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/resilience4j/Resilience4jRetryWithRecovery.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/config/BdkConfigTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/BdkRetryConfigTestHelper.java, symphony-bdk-core/src/test/resources/config/config.yaml, symphony-bdk-core/src/test/resources/config/df_retry_config.yaml
Closes https://github.com/finos/symphony-bdk-java/issues/464
Now datafeed is by default configured to have an infinite number of retry attempts. Global retry configuration keeps the same default value (`10`).
=> #464 Infinite number of attempts for the Datafeed retry configuration

symphony-bdk-bom/build.gradle, symphony-bdk-core/build.gradle, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-multi-instances-example/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle
This fixes security vulnerabilities reported by Snyk.
Along the way we lost the javax.annotation.Generated classes, add it
explicitly as a dependency.
=> Update Spring Boot to 2.4.3

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java
A ConcurrentModificationException can happen in the Datafeed (DF) loop upon startup.
The access to the listeners collection in the DF loop is not protected
and accessed by multiple threads.
Because of the for loop we need to synchronize on the list itself.
Fixes #475
=> Fix ConcurrentModificationException in Datafeed loop #475

build.gradle, symphony-bdk-bom/build.gradle, symphony-bdk-core/build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-multi-instances-example/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle
- Backport of #475 to 2.1-rc branch
- Bump version to 2.1.3
=> Backport of #475 and prepare release 2.1.3

docs/spring-boot/app-starter.md, symphony-bdk-examples/bdk-app-spring-boot-example/src/main/resources/application.yaml, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/auth/CircleOfTrustController.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/properties/JwtCookieProperties.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/auth/CircleOfTrustControllerTest.java
Closes #483
The request to /bdk/v1/app/auth appears to be vulnerable
to cross-site request forgery (CSRF) attacks against authenticated users.
The request can be issued cross-domain.
The BDK relies solely on HTTP cookies to identify the user that issued the request.
The request performs some privileged action within the application, which returns a token.
The attacker can determine all the parameters required to construct a request that
performs the action. If the request contains any values that the attacker cannot
determine or predict, then it is not vulnerable.
Setting the SameSite=Strict will prevent sending the cookie when the request is done from another domain.
=> #483 Jwt Cookie set with SameSite=Strict

docs/spring-boot/app-starter.md, symphony-bdk-examples/bdk-app-spring-boot-example/src/main/resources/application.yaml, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/auth/CircleOfTrustController.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/properties/JwtCookieProperties.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/auth/CircleOfTrustControllerTest.java
Backporting change: Jwt Cookie set with SameSite=Strict (#486)
=> Backporting: #483 Jwt Cookie set with SameSite=Strict (#486)

docs/configuration.md
DFv2 is using long polling and the agent is not storing any feedId (as for DFv1) so there’s no need to always call the same instance of the Agent for a given feedId. That's why the stickiness of a load balancer is only needed in case of DFv1.
No dependency on this PR.
=> Clarify stickiness on Agent LB is only needed for DFv1

symphony-bdk-bom/build.gradle, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-multi-instances-example/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle, symphony-bdk-http/symphony-bdk-http-webclient/build.gradle
reactor-spring does not seem to be required and is introducing a
dependency on json-smart that has a high vulnerability.
Closes #500 #499 #498 #497
=> Whitesource: remove unused dependency

symphony-bdk-core/src/test/java/com/symphony/bdk/core/retry/resilience4j/Resilience4jRetryWithRecoveryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1Test.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/ApiException.java, symphony-bdk-http/symphony-bdk-http-api/src/test/java/com/symphony/bdk/http/api/ApiExceptionTest.java
Fixes https://github.com/finos/symphony-bdk-java/issues/504
We recently noticed that the DatafeedLoop was crashing with `500` errors returned from Agent. This is something we initially stated that we did not wanted to retry on this specific status. Now we do :) It has actually been raised by some customers. 
Will have to be backported to `2.1-rc` branch.
=> #504 DatafeedLoop now retries on 500 server errors

symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/util/ApiUtils.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClient.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClientTest.java
[#513 ](https://github.com/finos/symphony-bdk-java/issues/513)
In order to help developers to debug ssl certs issues, a log has been added when the certs are loaded from the trustStore.
=> #513 log ssl certs loaded by the bot

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/ActivityRegistry.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/HelpCommand.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/SlashCommand.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/model/ActivityInfo.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/ActivityRegistryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/TestCommandActivity.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/CommandActivityTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/SlashCommandTest.java
[#515 ](https://github.com/finos/symphony-bdk-java/issues/515)
Previously, we were not able to register two slash commands having the same name. This was done in order to avoid registering duplicates. However, two slash commands having the same name are not necessarily duplicates as they can differ in bot's mention required property : In fact, we can have one command requiring bot's mention while the second one is not requiring it. In this case, both of them should be registered. 
The issue was coming from the fact that we only relied on command's name to check if it is not already present in the registry. The fix was to check the bot's mention required property as well.
=> #515 Unable to create SlashHandler with same value, different @mention

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
[#517](https://github.com/finos/symphony-bdk-java/issues/517)
User service methods to search users cause null pointer when no user is found.
The endpoint /v3/users to search users return null with 204 (no content) http code when no user is found.
This endpoint is used in user service to search users by ids, emails and usernames.
The null pointer was comming from User service methods that call getUsers() on the returned object, which causes NP when no user is found.
There were two options to fix this :
- throw an exception when no user is found
- return an empty list
The second option was chosen to fix this bug. Thus, User service returns an empty list when no user found.
=> #517 List users method does not handle bad path.

symphony-bdk-bom/build.gradle
Backport of commit #521 : Upgraded jersey dependency to 2.34
=> PLAT-10897 (backport) Upgraded jersey dependency to 2.34 (#522)

symphony-bdk-core/src/main/java/com/symphony/bdk/core/ServiceFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/RealTimeEventListener.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/ServiceFactoryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1Test.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkDatafeedConfig.java
[PLAT-10923](https://perzoinc.atlassian.net/browse/PLAT-10923)
To be able to handle external messages we want to use userId instead of username to accept incoming events.
- [] Unit tests updated or added
=> PLAT-10923: Usage of userId instead of username to accept incoming events

build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/ServiceFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/RealTimeEventListener.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/ServiceFactoryTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1Test.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkDatafeedConfig.java
[PLAT-10923](https://perzoinc.atlassian.net/browse/PLAT-10923)
To be able to handle external messages we want to use userId instead of username to accept incoming events.
=> PLAT-10923 Usage of userId instead of username to accept incoming events (2.1-rc manual backport)

build.gradle, symphony-bdk-bom/build.gradle, symphony-bdk-http/symphony-bdk-http-jersey2/build.gradle
Dependency `org.glassfish.jersey.media:jersey-media-json-jackson` was importing transitive `org.glassfish.jersey.core:jersey-common:2.32` instead of `org.glassfish.jersey.core:jersey-common:2.34` which seems to be an issue in Jersey side.
We might have to open a ticket on their repo.
=> PLAT-10897 fixed jersey common dependency issue

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/HelpCommand.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/HelpCommandTest.java
This PR is related to [#533](https://github.com/finos/symphony-bdk-java/issues/533)
The build-in help command lists the existing commands. Previously, it was not adding the help command itself in the list. The filter has been changed in this commit to get return it in the list
=> PLAT-10920 : Return built-in help command in the list of commands

symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/test/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2Test.java
When a proxy is used, the Jersey client was switch to the Apache HTTP
connection pool which was not properly configured to use custom
key/trust stores.
The connector has to be set all the time to make the Apache pool is
used. Then the SSL context must be set directly in the pool as well.
Added a unit test to check this using Mock Server.
Closes #519
=> Jersey HTTP client SSL/TLS broken configuration

symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/ApiClientFactory.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/ApiClientBuilder.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/test/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2Test.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClient.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClientTest.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientWebClientTest.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/test/BdkMockServer.java
The HTTP clients implementations supported by the BDK both support
registering custom filters to intercept requests and responses. This can
be useful to add custom logic, trace requests, provide metrics or
support use cases such as Agentless.
Using the SymphonyBdkBuilder it is now possible to register such
filters.
For instance:
```java
final SymphonyBdk bdk = new SymphonyBdkBuilder()
.apiClientFactory(new ApiClientFactory(config){
@Override
protected ApiClientBuilder getApiClientBuilder(String basePath, BdkClientConfig clientConfig) {
ApiClientBuilder apiClientBuilder = super.getApiClientBuilder(basePath, clientConfig);
apiClientBuilder.addFilter(new JerseyCryptoFilter(config));
return apiClientBuilder;
}
})
.config(config)
.build();
```
The concrete implementation is specifc to each …
=> Support client/response filters for HTTP clients

symphony-bdk-bot-sdk-java/src/main/java/com/symphony/bdk/bot/sdk/monitoring/SymphonyHealthMeterBinder.java, symphony-bdk-bot-sdk-java/src/test/java/com/symphony/bdk/bot/sdk/monitoring/SymphonyHealthMeterBinderTest.java
Startup would fail with this error:
Caused by: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
at io.micrometer.core.instrument.ImmutableTag.<init>(ImmutableTag.java:35) ~[micrometer-core-1.5.1.jar!/:1.5.1]
at io.micrometer.core.instrument.Tag.of(Tag.java:29) ~[micrometer-core-1.5.1.jar!/:1.5.1]
at com.symphony.bdk.bot.sdk.monitoring.SymphonyHealthMeterBinder.bindTo(SymphonyHealthMeterBinder.java:51) ~[symphony-bdk-bot-sdk-java-1.3.4.jar!/:1.3.4]
at org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryConfigurer.lambda$addBinders$1(MeterRegistryConfigurer.java:84) ~[spring-boot-actuator-autoconfigure-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_265] …
=> PLAT-11065: Failing healthcheck could prevent bot's startup

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/util/PresentationMLParser.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/util/PresentationMLParserTest.java
closes #544 
Goal of this PR is to enable the BDK to extract content from a presentationML which contains HTML specific tags.
=> #544 Remove html entities before xml parsing messages

symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/util/ApiUtils.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClient.java
#547 
Goal of this pr is to load both custom and system truststore while creating the SSL context.
=> Load system truststore in the SSL Context

symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/ApiClientFactory.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/ApiClientBuilder.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/test/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2Test.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClient.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClientTest.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientWebClientTest.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/test/BdkMockServer.java
This reverts commit 22c12e9b7817ef9e11fcb131c65c6cd3cd862bd0.
PLAT-11140
This reverts #542 as agentless project is now in standby.
- [N/A] Unit tests updated or added
=> PLAT-11140: Revert "Support client/response filters for HTTP clients (#542)"

symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecoveryBuilder.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1Test.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java
The datafeed loop could stop if DNS related exception were raised (which
could happen because of network glitches or after an outage).
Similar to the timeoutout or connect error we prefer to keep the DF loop
running and to retry.
Note that for DFv2 on startup a DNS error will prevent the DF loop to
start (same as a connect error).
For DFv1 a DNS error will still allow the DF loop to start (if the DF id
already exists) this is consistent with the existing behavior for
connect errors.
Fixes PLAT-11178
=> Keep DF loop running for UnknownHostException

docs/spring-boot/core-starter.md, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkDatafeedConfig.java
Running the application event consumer asynchronously is not always preferable,
this feature will give the a better control on that to BDK client.
Example:
bdk:
datafeed:
async: false
[561](https://github.com/finos/symphony-bdk-java/issues/561)
=> Feature-561: Make ApplicationEventMulticaster bean configurable

symphony-bdk-http/symphony-bdk-http-jersey2/build.gradle, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/test/java/com/symphony/bdk/http/jersey2/ApiClientJersey2Test.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientWebClient.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientWebClientTest.java
PR https://github.com/finos/symphony-bdk-java/pull/489 has introduced a regression where the `ApiClientJersey2` stopped initializing the `traceId` value if not already set: 
Here we revert this change but we now ensure that the `traceId` is cleared in order to not pollute subsequent logs.
=> ApiClientJersey2 initialize random traceId if not already set

docs/message.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/model/SortDir.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/SearchMessageExampleMain.java
Closes #566
Support of [Search Messages endpoint](https://developers.symphony.com/restapi/reference#message-search-post).
Also added so pre-validation checks following [public documentation](https://developers.symphony.com/restapi/reference#message-search-post).
Decided to implement the `POST` version only, as it allows to use the generated `MessageSearchQuery` class. The `POST` endpoint is completely similar to the `GET` one.
=> #566 Support of Search Messages endpoint (using POST)

symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/jwt/JwtHelper.java
If the backend and the bot/BDK do not have their clocks synced, the
signed JWT generated to authenticate could be considered as invalid
because the expiration is considered to be more then 5 minutes by the
backend.
We use 4 minutes instead to accommodate that.
Given we create a new token for each authentication attempt this should
be fine to use less than 5 minutes (we expect the signed JWT to be used
quickly).
=> Prevent invalid signed JWT expiration upon login

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/connection/ConnectionService.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/connection/OboConnectionService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/connection/ConnectionServiceTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/test/MockApiClient.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/Pair.java
Following our [official documentation](https://symphony.readme.io/restapi/reference#list-connections), the `ConnectionService#listConnections(ConnectionStatus, List<Long>)` are now optional and can therefore be set to `null`. 
Also took the opportunity to improve testing of query params that can now be asserted when using the `MockApiClient`.
=> Optional ConnectionService#listConnections parameters

docs/message.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/message/MessageServiceTest.java, symphony-bdk-core/src/test/resources/message/update_message.json, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/MessageUpdateExampleMain.java
Added new message update endpoint to `MessageService` class.
- Mentioned in markdown doc 
- Simple demo created (`MessageUpdateExampleMain.java`). I'd like make it a bit more fun so I'll modify it before merging this PR
----
=> [beta] Support of message update endpoint

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/stream/StreamService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/stream/StreamServiceTest.java
Goal of this implementation is to encode when needed to url safe base 64 stream or msg ids. Updated endpoints are:
- updateRoom -> pinned message id inside the input payload
- updateInstantMessage -> both pinned message id inside the input payload and the imId from the path
- getInstantMessageInfo -> imId from the path
=> Encode ids to url-safe in pin message context

symphony-bdk-template/symphony-bdk-template-freemarker/src/main/java/com/symphony/bdk/template/freemarker/FreeMarkerEngine.java, symphony-bdk-template/symphony-bdk-template-freemarker/src/test/java/com/symphony/bdk/template/freemarker/FreeMarkerTemplateTest.java, symphony-bdk-template/symphony-bdk-template-freemarker/src/test/resources/subFolder/testWithLong.ftl, symphony-bdk-template/symphony-bdk-template-freemarker/src/test/resources/subFolder/testWithObject.ftl
- Enforcing numbers format to not add , or . in between. Before while using numbers, freemarker was formatting them from "123456" to "123,456" this was causing issues especially when dealing with userIds.
- Enforcing freemarker to access beans object fields without the need to specify the get in the variable. Before only this definition was working ${event.getParameter().getAnother()}, now also this one will work: ${event.parameter.another}
=> Improving freemarker template engine configuration

symphony-bdk-core/src/test/java/com/symphony/bdk/core/gen/GeneratedEnumTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java, symphony-bdk-core/src/test/resources/user/user_detail_unknown_account_type.json, templates/modelInnerEnum.mustache
Closes https://github.com/finos/symphony-bdk-java/issues/592
We want to avoid response parsing issues when API returns an unknown enum value. The `modelInnerEnum.mustache` template has been modified in order to: 
- return null
- print warning log
=> #592 Generated enums don't throw exception when parsing unknown values

symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/loadbalancing/ExternalLoadBalancingStrategy.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecovery.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/retry/RetryWithRecoveryBuilder.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/retry/resilience4j/Resilience4jRetryWithRecoveryTest.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java
This PR brings some improvements in the Datafeed loop strategy, especially when Agent goes down in an unexpected way. The `RetryWithRecoveryBuilder` will now look deeper in the root exception causes and try to detect if the root cause is a `SocketException`. 
On the `ApiClientJersey2` side, we now catch potential `NoHttpResponseException` that can be thrown in similar situation. and wrap them as `SocketException`.
=> Improved DF loop retry strategy by supporting SocketException found in root exception causes

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/user/UserService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/user/UserServiceTest.java
Related to https://github.com/finos/symphony-bdk-java/issues/598, we decided to ease the usage of this endpoint by providing two different functions to suspend/unsuspend a user account.
- suspendUser(userId, reason, until)
- unsuspendUser(userId)
=> Support user suspension API

docs/activity-api.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/exception/SlashCommandSyntaxException.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/SlashCommandPattern.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/parsing/SlashCommandPatternTest.java
#511
Added a check to verify argument names are unique in a slash command definition.
=> #511: added a check for argument name unicity in slash command pattern

docs/spring-boot/core-starter.md, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/CommandContext.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/SlashCommand.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/Arguments.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/CommandToken.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/MatchingUserIdMentionToken.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/RegexCommandToken.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/SlashCommandPattern.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/TypedArgumentToken.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/SlashCommandTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/parsing/MatchingUserIdMentionTokenTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/parsing/SlashCommandPatternTest.java, symphony-bdk-examples/bdk-spring-boot-example/src/main/java/com/symphony/bdk/examples/spring/EchoActivity.java, symphony-bdk-examples/bdk-spring-boot-example/src/test/java/com/symphony/bdk/examples/spring/arch/ArchitectureTest.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/annotation/Slash.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/annotation/SlashAnnotationProcessor.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/annotation/SlashAnnotationProcessorTest.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/slash/TestSlashCommand.java
#511
Make slash command arguments available in annotated methods with @Slash in SB starter
=> #511 Make slash command arguments available in SB starter

symphony-bdk-bom/build.gradle, symphony-bdk-core/build.gradle
Upgrade logback for https://jira.qos.ch/browse/LOGBACK-1591 (minor CVE)
Set log4j version to 2.16 in the BOM in case bot developers are using
the spring boot log4j starter for instance. By default the BDK is not
using log4j and is thereforce not affected by log4shell
(CVE-2021-44228).
Upgrade Jackson, Lombok, Bouncycastle, Junit, AssertJ, mapstruct too.
=> Upgrade dependencies

symphony-bdk-bom/build.gradle
Reminder: BDK is not using log4j directly but defines its preferred
version in the BOM in case it used by BDK users via the spring boot
log4j starter for instance.
Upgrade to 2.17.0 for CVE-2021-45105
=> Upgrade log4j preferred version in BOM

symphony-bdk-core/src/main/java/com/symphony/bdk/core/client/loadbalancing/LoadBalancedApiClient.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/ApiClient.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/ApiClientBuilder.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/auth/Authentication.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientBuilderJersey2.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/test/java/com/symphony/bdk/http/jersey2/ApiClientJersey2Test.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientBuilderWebClient.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientWebClient.java, symphony-bdk-http/symphony-bdk-http-webclient/src/test/java/com/symphony/bdk/http/webclient/ApiClientWebClientTest.java
The `ApiClient` interface now allows to configure a list of authentication schemes, according to the [OpenAPI specification](https://swagger.io/docs/specification/authentication). 
This will especially be useful for the support of CommonJwt (i.e. OAuth) authentication.
=> ApiClient supports authentication schemes

symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkDatafeedConfig.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkOboServiceConfig.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/events/RealTimeEventListenerAsyncTest.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/events/RealTimeEventsAsyncTestListener.java
Closes #614 
This commit allows to copy the MDC values from the parent thread to the child
thread through a task decorator, otherwise the MDC values, especially the trace
id is lost, hence the tracibility is broken.
N/A
=> #614 Add a decorator to the  ApplicationEventMulticaster

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/form/FormReplyActivity.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/form/FormReplyContext.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/AbstractActivityTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/form/FormReplyActivityTest.java
Closes #621
2 new fields added to the `FormReplyActivity` class: 
- `streamId`
- `formMessageId`
=> #621 Added streamId and formMessageId to FormReplyActivity

docs/configuration.md
PLAT-11772
Added a proxy configuration example where proxy is only configured for the agent.
- [N/A] Unit tests updated or added
=> Added proxy configuration example

symphony-bdk-core/build.gradle
Goal of this PR is to start targeting a specific commit of the [Symphony-api-spec](https://github.com/finos/symphony-api-spec) repository and not always target the master branch, this way we'll have more control over compatibility and what features are included in each BDK version.
Also since from 20.14 we are starting deprecation process of apps authentication endpoint using certificate, we are going to generate the code from the authenticator-api-public-deprecated.yaml file so that we still support those APIs.
=> Target specific commit for symphony-api-specs

symphony-bdk-http/symphony-bdk-http-api/build.gradle, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/HttpClient.java, symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/util/ApiUtils.java, symphony-bdk-http/symphony-bdk-http-api/src/test/java/com/symphony/bdk/http/api/HttpClientTest.java, symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java, symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientWebClient.java
=> Supported a list of files in multipart form data

symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/MessageExampleMain.java
Starting from Agent 20.14 we are now able to use the already existing [Import Message API](https://developers.symphony.com/restapi/reference/import-message-v4) to import attachments as well along with the message.
A list of attachments can be added to the V4ImportedMessage object providing for each attachment:
- **filename** (with the file extension) 
- **file content** in base64 format
=> Example to import messages with attachments

symphony-bdk-core/build.gradle, symphony-bdk-extensions/symphony-group-extension/build.gradle
Also fix build warnings about etag for API specs.
Also update the url to symphony-api-spec and avoid using master to make
sure builds are reproductible.
N/A
- [N/A] Unit/Integration tests updated or added
=> Generate javadoc for group extension

docs/configuration.md, docs/datafeed.md, symphony-bdk-config/src/main/java/com/symphony/bdk/core/config/model/BdkDatafeedConfig.java, symphony-bdk-core/build.gradle, symphony-bdk-core/src/test/java/com/symphony/bdk/core/SymphonyBdkTest.java
The datafeed 1 service will be fully replaced by the datafeed 2 service in the future. Please consider migrating over to datafeed 2 APIs /agent/v5/datafeeds. For more information on the timeline as well as on the benefits of datafeed 2, please reach out to your Technical Account Manager or to our developer documentation https://docs.developers.symphony.com/building-bots-on-symphony/datafeed
This PR includes:
- if datafeed version is not defined in the config, the BDK will use DFv2 by default
- added deprecation notice when DFv1 is used
- APIs generation is been updated following swagger deprecation of the APIs https://github.com/finos/symphony-api-spec/pull/143
=> Starting Datafeed v1 deprecation process

symphony-bdk-bom/build.gradle, symphony-bdk-core/build.gradle, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle
Agent API is now returning the parentMessageId as part of V4Message
payloads to retrieve the original message in case of a forward or a
reply.
https://github.com/finos/symphony-api-spec/pull/150
=> Upgrade Symphony API specifications for parent message id / Upgrade Spring Boot to 2.6.7

docs/datafeed.md
Those events are not yet handled by the Agent so avoid mentioning them
in the documentation.
=> Remove unsupported Datahose events from documentation

symphony-bdk-bom/build.gradle, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle
Due to CVE2022-22978 vulnerability in spring-security-web-5.6.3,
springboot version has to be updated to 2.6.8 to get rid of
this issue.
=> Update springboot version

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java
The existing feed id does not have the suffix after '_f',
which does not matche with the regex pattern.
With this commit, the regex pattern will match the existing
DF ID as well as the new DF ID value (haveing the suffix
after '_f').
=> Fix DF2 ID format regex pattern bug

symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/AbstractExtensionAppAuthenticator.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorCertImpl.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/ExtensionAppAuthenticatorRsaImpl.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/impl/AbstractExtensionAppAuthenticatorTest.java
Closes #670 
ExtensionAppAuthenticatorRsaImpl class has 2 different api clients: login and pod api clients with different base paths. The overridden method getBasePath() always returns login pod api base path. 
When the api call to get pod certificate fails and gets retried, the getBasePath() is called to provide more info in the error message. In this case, the login pod api client base path is injected while the pod api client is the one being used. 
In this PR we separate both apis base path with 2 different methods to avoid confusion: 
Added two methods, one to get the basepath used to get pod certificate and another one to get the basepath used to authenticate and retrieve tokens.
=> #670: Retry error message does not use the correct api base path in AbstractExtensionAppAuthenticator

symphony-bdk-bom/build.gradle, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle
Upgrade SpringBoot version to latest 2.7.3 in order to fix some security vulnerabilities related to jetty.http2
=> Upgrade SpringBoot version to latest 2.7.3 

docs/migration.md
Fix jekyll code formatting in migration docs
=> Fix jekyll code formatting in migration docs

symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/command/SlashCommand.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/parsing/SlashCommandPattern.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/command/SlashCommandTest.java
Empty pattern was not allowed in the slash command, however the same is allowed in Python BDK.
This commit is to align with Python BDK, an empty pattern is enabled, a slash command has only the Bot mention is now possible.
=> Enable empty slash command pattern

symphony-bdk-template/symphony-bdk-template-api/src/main/java/com/symphony/bdk/template/api/TemplateEngine.java, symphony-bdk-template/symphony-bdk-template-freemarker/src/main/java/com/symphony/bdk/template/freemarker/FreeMarkerEngine.java, symphony-bdk-template/symphony-bdk-template-freemarker/src/test/java/com/symphony/bdk/template/freemarker/FreeMarkerTemplateTest.java, symphony-bdk-template/symphony-bdk-template-handlebars/src/main/java/com/symphony/bdk/template/handlebars/HandlebarsEngine.java, symphony-bdk-template/symphony-bdk-template-handlebars/src/test/java/com/symphony/bdk/template/handlebars/HandlebarsEngineTest.java
This commit provides the inline template support in TemplateEgine, so that the template can be initiated not only from a file, but could be also from a template string.
=> Add inline template support in TemplateEngine

docs/datafeed.md, symphony-bdk-config/src/main/java/com/symphony/bdk/core/config/model/BdkDatahoseConfig.java, symphony-bdk-core/build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatahoseLoopImpl.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatahoseLoopTest.java
In the new update of Datahose api, the field filters has been renamed to eventTypes. In this commit, we apply this update in BDK Python.
The generated code has been updated as well according to the last changes in symphony-api-specs.
=> Fix Datahose loop 

allow-list.xml, build.gradle, docs/health.md, docs/spring-boot/app-starter.md, symphony-bdk-bom/build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/DatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/AbstractDatafeedLoop.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/health/HealthService.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/health/HealthServiceTest.java, symphony-bdk-examples/bdk-app-spring-boot-example/src/main/resources/application.yaml, symphony-bdk-http/symphony-bdk-http-jersey2/build.gradle, symphony-bdk-http/symphony-bdk-http-webclient/build.gradle, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/build.gradle, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkExtAppControllerConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicator.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkExtAppControllerConfigTest.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicatorTest.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkServiceConfig.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/SymphonyBdkAutoConfigurationTest.java
The health endpoint uses the HealthService to provide the core components health status, as well as the DatafeedLoop running process status, if the running process counter is not updated in a fixed time range, the process is considered as 'DOWN'.
=> Add actuator health endpoint to app starter

docs/datafeed.md, symphony-bdk-config/src/main/java/com/symphony/bdk/core/config/model/BdkDatafeedConfig.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java
The Datafeed tag is an internal feature and the tag property is optional in the configuration. So far, when no tag is configured, the bot username was used as a tag. This leads to production issues when the tag is an old hanging one. In this PR, we only set the tag in Datafeed calls when it is provided in configuration, otherwise a null value is put. For the same occasion, I corrected the Datafeed documentation with some links returning a 404 page error. The tag property is not documented as it is only internal feature.
=> #680: not set bot username as Datafeed tag

symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicator.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicatorTest.java
CE health status is optional, should not impact the BDK bot global health status, remove it from the check list.
Closes #[[742](https://github.com/finos/symphony-bdk-java/issues/742)]
=> Remove CE health check from the indicator

symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkExtAppTracingFilterConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkExtAppTracingFilterConfigTest.java
Make the tracing filter order as highest so it will generate the tracing id at the very beginning of the request process.
Closes #[[743](https://github.com/finos/symphony-bdk-java/issues/743)]
=> Change tracing filter's order in the registration

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java
When reading DF events fails with client error 400, the API call is doing a retry by recreating the DF, the DF recreation API call unfortunately does not have a retry on client error.
This commit fixed this bug.
=> Make DF recreation retry when client error

allow-list.xml, docs/datafeed.md, docs/spring-boot/core-starter.md, docs/test.md, symphony-bdk-core/build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/AbstractActivity.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/activity/ActivityContext.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/EventPayload.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/RealTimeEventType.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/activity/AbstractActivityTest.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1Test.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV2Test.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatahoseLoopTest.java, symphony-bdk-examples/bdk-core-examples/src/main/java/com/symphony/bdk/examples/DatafeedExampleMain.java, symphony-bdk-examples/bdk-spring-boot-example/src/main/java/com/symphony/bdk/examples/spring/EchoActivity.java, symphony-bdk-examples/bdk-spring-boot-example/src/main/java/com/symphony/bdk/examples/spring/RealTimeEventsDemo.java, symphony-bdk-examples/bdk-spring-boot-example/src/test/java/com/symphony/bdk/examples/spring/SampleSpringAppIntegrationTest.java, symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/SymphonyBdkTestUtils.java
The event timestamp is filled at the event wrapper level only, which is the one when the event is read from datafeed. However only the raw event is pushed to the real time listeners, that's the reason why we loose this event timestamp.
This commit fix this issue by constructing an event proxy at runtime, all events implements EventPayload interface, the timestamp value is now accessible through this interface. User has to cast the raw event to EventPayload to read the value. This big advantage is we do not bring in any breaking changes in any stable APIs, the change is totally transparent for the BDK developers.
Closes #[741](https://github.com/finos/symphony-bdk-java/issues/741)
=> Fix the event timestamp value is not accessible bug

.github/workflows/release.yml, build.gradle
=> Update publish gradle plugin

symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicator.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicatorTest.java
When extended health info api returns 5xx, the response body cannot be parsed into json model, in this case, we should consider all compoments are down.
=> Fix health info parsing bug

.github/workflows/docs.yml, .github/workflows/gradle-wrapper-validation.yml, buildSrc/src/main/groovy/bdk.java-common-conventions.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/RealTimeEventType.java
The byte-buddy default classloading strategy requires the access to Java internal methods, which are sealed by JPMS since Jdk11. The fix is to change the strategy from default one to UsingLookup, according to the recommendation of byte-buddy doc.
Add "Automatic-Module-Name" attribute in main MANIFEST.MF entry.
=> Fix byte-buddy class loading failure

allow-list.xml, symphony-bdk-bom/build.gradle, symphony-bdk-examples/bdk-multi-instances-example/build.gradle
- Update resilience4j to latest version in order to adapt the spring boot 3.x upgrade.
- Update spring boot to 3.0.x latest version
- Update hazelcast and jackson-databind version
=> Update resilience and spring boot version

allow-list.xml, build.gradle, symphony-bdk-bom/build.gradle, symphony-bdk-examples/bdk-app-spring-boot-example/build.gradle, symphony-bdk-examples/bdk-spring-boot-example/build.gradle, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/SymphonyBdkAppAutoConfiguration.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkExtAppControllerConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkExtAppSecurityConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkHealthIndicatorConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicator.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/resources/META-INF/spring.factories, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkExtAppControllerConfigTest.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkExtAppSecurityConfigTest.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkHealthIndicatorConfigTest.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicatorTest.java, symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/SymphonyBdkTestUtils.java
- Updated SpringBoot to 3.2.2 to fix CVE-2024-22233
- Fix springboot autoconfiguration config bug in app starter
=> Update Springboot to 3.2.2

.github/workflows/build.yml, docs/_config.yml, docs/index.md, docs/migration.md
=> Update reference doc for BDK release 3.0

docs/index.md
=> Adapt the blockquote to gitbook format

.github/workflows/build.yml, .github/workflows/cve-scanning-gradle.yml, .github/workflows/docs.yml, .github/workflows/gradle-wrapper-validation.yml, .github/workflows/release.yml, .github/workflows/semgrep.yml, README.md, docs/index.md
- Update github actions version to use node.js 20, as recommended by github
- Update README.md to publish BDK 3.0 breaking changes
=> Update github actions version and README.md

symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/config/BdkHealthIndicatorConfig.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/main/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicator.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/config/BdkHealthIndicatorConfigTest.java, symphony-bdk-spring/symphony-bdk-app-spring-boot-starter/src/test/java/com/symphony/bdk/app/spring/service/SymphonyBdkHealthIndicatorTest.java
Separate DataFeedLoop health check from the other components, set the global status to out of service only if DataFeedLoop is down. In this case, when calling health check endpoint, the response http code is 503, otherwise if any other components is down, set the global status to "WARNING", the http code of the response stays as 200.
This will avoid unnecessary BDK Bot restarting when other components are not healthy.
Remove the custom status code mapper, and use the default mapping behaviour of Spring Boot.
=> Update health check status code strategy

symphony-bdk-bom/build.gradle, symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/jwt/JwtHelper.java
We are downgrading the JJWT library to 0.9.1 to prevent JWT validation failure.
The latest JJWT library is enforcing the "sub" claim to be "string" data format (which is according to the RFC standard). This check makes the validation of the extension application JWT to fail because the "sub" claim is of long data type, equal to the Symphony user id. 
This check is not enforced in the JJWT 0.9.1 library version thus we are using that version.
Additionally:
- fix https://spring.io/security/cve-2024-22243
none
=> Downgrade JJWT library version

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/MessageService.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/message/OboMessageService.java
This commit updates the OboMessageService so that a BDK bot can update a message on behalf of someone (along with OBO message send and OBO message delete).
=> Add update message in OboMessageService

docs/datafeed.md
EOL datafeed 1 and improve datahose page
=> EOL datafeed 1 and improve datahose page

symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/RealTimeEventListener.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/service/datafeed/impl/RealTimeEventType.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/service/datafeed/impl/DatafeedLoopV1Test.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/events/RealTimeEventsDispatcher.java, symphony-bdk-test/symphony-bdk-test-jupiter/src/main/java/com/symphony/bdk/test/SymphonyBdkTestUtils.java
Starting with Agent 24.6.1, a new type of event called `GENERICSYSTEMEVENT` may be received via datafeed.
Goal of this change is to support them in Spring event listener to ease their consumption.
None
=> AGNT-598: support GENERICSYSTEMEVENTs in listeners

symphony-bdk-bom/build.gradle
Upgrade spring-book-starter-tomcat from 3.3.6 to 3.3.7 to fix https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-8523186
=> upgrade spring boot from 3.3.6 to 3.3.7 to fix vulnerability

build.gradle
[UPL-160](https://perzoinc.atlassian.net/browse/UPL-160)
=> UPL-160: update OSSRH URI to push to MavenCentral

symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdk.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/SymphonyBdkBuilder.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/AuthenticatorFactory.java, symphony-bdk-core/src/main/java/com/symphony/bdk/core/auth/impl/AuthenticatorFactoryImpl.java, symphony-bdk-core/src/test/java/com/symphony/bdk/core/auth/AuthenticatorFactoryTest.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/main/java/com/symphony/bdk/spring/config/BdkCoreConfig.java, symphony-bdk-spring/symphony-bdk-core-spring-boot-starter/src/test/java/com/symphony/bdk/spring/config/BdkCoreConfigTest.java
Introduced the `AuthenticatorFactory` as an interface so that different implementations for authenticators can be defined in user projects.
=> Introduced AuthenticatorFactory interface

.github/workflows/cve-scanning-gradle.yml, build.gradle
=> Adding NVD api key to fix CVEs scanning issue
